/*
SimpleBilly API

Testing WarehouseAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package simplebillyapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_simplebillyapi_WarehouseAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WarehouseAPIService CreateWarehouse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WarehouseAPI.CreateWarehouse(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarehouseAPIService DeleteWarehouse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var warehouseId string

		httpRes, err := apiClient.WarehouseAPI.DeleteWarehouse(context.Background(), warehouseId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarehouseAPIService GetWarehouse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var warehouseId string

		resp, httpRes, err := apiClient.WarehouseAPI.GetWarehouse(context.Background(), warehouseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarehouseAPIService ListWarehouses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WarehouseAPI.ListWarehouses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarehouseAPIService UpdateWarehouse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var warehouseId string

		resp, httpRes, err := apiClient.WarehouseAPI.UpdateWarehouse(context.Background(), warehouseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
