/*
SimpleBilly API

Testing ShipmentAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package simplebillyapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_simplebillyapi_ShipmentAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShipmentAPIService CreateShipment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShipmentAPI.CreateShipment(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService CreateShipmentFromOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderNumber string

		resp, httpRes, err := apiClient.ShipmentAPI.CreateShipmentFromOrder(context.Background(), orderNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService DeleteShipment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		httpRes, err := apiClient.ShipmentAPI.DeleteShipment(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService GetShipment", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		resp, httpRes, err := apiClient.ShipmentAPI.GetShipment(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService ListShipments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShipmentAPI.ListShipments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService TrackOrderPublic", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShipmentAPI.TrackOrderPublic(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService TrackShipmentApi", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		resp, httpRes, err := apiClient.ShipmentAPI.TrackShipmentApi(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShipmentAPIService UpdateShipmentStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shipmentId string

		resp, httpRes, err := apiClient.ShipmentAPI.UpdateShipmentStatus(context.Background(), shipmentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
