/*
SimpleBilly API

Testing SupplierInvoiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package simplebillyapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_simplebillyapi_SupplierInvoiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SupplierInvoiceAPIService CreateSupplierInvoice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SupplierInvoiceAPI.CreateSupplierInvoice(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplierInvoiceAPIService DeleteSupplierInvoice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var supplierInvoiceId string

		httpRes, err := apiClient.SupplierInvoiceAPI.DeleteSupplierInvoice(context.Background(), supplierInvoiceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplierInvoiceAPIService GetSupplierInvoice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var supplierInvoiceId string

		resp, httpRes, err := apiClient.SupplierInvoiceAPI.GetSupplierInvoice(context.Background(), supplierInvoiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplierInvoiceAPIService ListSupplierInvoices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SupplierInvoiceAPI.ListSupplierInvoices(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplierInvoiceAPIService UpdateSupplierInvoice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var supplierInvoiceId string

		resp, httpRes, err := apiClient.SupplierInvoiceAPI.UpdateSupplierInvoice(context.Background(), supplierInvoiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplierInvoiceAPIService UpdateSupplierInvoiceStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var supplierInvoiceId string

		resp, httpRes, err := apiClient.SupplierInvoiceAPI.UpdateSupplierInvoiceStatus(context.Background(), supplierInvoiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
