/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"fmt"
)

// LanguageCode the model 'LanguageCode'
type LanguageCode string

// List of LanguageCode
const (
	DE LanguageCode = "DE"
	EN LanguageCode = "EN"
	FR LanguageCode = "FR"
	ES LanguageCode = "ES"
	IT LanguageCode = "IT"
	NL LanguageCode = "NL"
	PL LanguageCode = "PL"
	PT LanguageCode = "PT"
	TR LanguageCode = "TR"
	RU LanguageCode = "RU"
	UK LanguageCode = "UK"
	CS LanguageCode = "CS"
	EL LanguageCode = "EL"
	HU LanguageCode = "HU"
	RO LanguageCode = "RO"
	SV LanguageCode = "SV"
	DA LanguageCode = "DA"
	FI LanguageCode = "FI"
	NO LanguageCode = "NO"
	SK LanguageCode = "SK"
	SL LanguageCode = "SL"
	HR LanguageCode = "HR"
	BG LanguageCode = "BG"
	ET LanguageCode = "ET"
	LV LanguageCode = "LV"
	LT LanguageCode = "LT"
	MT LanguageCode = "MT"
	AR LanguageCode = "AR"
	ZH LanguageCode = "ZH"
	JA LanguageCode = "JA"
	KO LanguageCode = "KO"
	TH LanguageCode = "TH"
	VI LanguageCode = "VI"
	ID LanguageCode = "ID"
	HI LanguageCode = "HI"
	AB LanguageCode = "AB"
	AA LanguageCode = "AA"
	AF LanguageCode = "AF"
	AK LanguageCode = "AK"
	SQ LanguageCode = "SQ"
	AM LanguageCode = "AM"
	AN LanguageCode = "AN"
	HY LanguageCode = "HY"
	AS LanguageCode = "AS"
	AV LanguageCode = "AV"
	AE LanguageCode = "AE"
	AY LanguageCode = "AY"
	AZ LanguageCode = "AZ"
	BM LanguageCode = "BM"
	BA LanguageCode = "BA"
	EU LanguageCode = "EU"
	BE LanguageCode = "BE"
	BN LanguageCode = "BN"
	BI LanguageCode = "BI"
	BS LanguageCode = "BS"
	BR LanguageCode = "BR"
	MY LanguageCode = "MY"
	CA LanguageCode = "CA"
	CH LanguageCode = "CH"
	CE LanguageCode = "CE"
	NY LanguageCode = "NY"
	CU LanguageCode = "CU"
	CV LanguageCode = "CV"
	KW LanguageCode = "KW"
	CO LanguageCode = "CO"
	CR LanguageCode = "CR"
	DV LanguageCode = "DV"
	DZ LanguageCode = "DZ"
	EO LanguageCode = "EO"
	EE LanguageCode = "EE"
	FO LanguageCode = "FO"
	FJ LanguageCode = "FJ"
	FY LanguageCode = "FY"
	FF LanguageCode = "FF"
	GD LanguageCode = "GD"
	GL LanguageCode = "GL"
	LG LanguageCode = "LG"
	KA LanguageCode = "KA"
	KL LanguageCode = "KL"
	GN LanguageCode = "GN"
	GU LanguageCode = "GU"
	HT LanguageCode = "HT"
	HA LanguageCode = "HA"
	HE LanguageCode = "HE"
	HZ LanguageCode = "HZ"
	HO LanguageCode = "HO"
	IS LanguageCode = "IS"
	IO LanguageCode = "IO"
	IG LanguageCode = "IG"
	IA LanguageCode = "IA"
	IE LanguageCode = "IE"
	IU LanguageCode = "IU"
	IK LanguageCode = "IK"
	GA LanguageCode = "GA"
	JV LanguageCode = "JV"
	KN LanguageCode = "KN"
	KR LanguageCode = "KR"
	KS LanguageCode = "KS"
	KK LanguageCode = "KK"
	KM LanguageCode = "KM"
	KI LanguageCode = "KI"
	RW LanguageCode = "RW"
	KY LanguageCode = "KY"
	KV LanguageCode = "KV"
	KG LanguageCode = "KG"
	KJ LanguageCode = "KJ"
	KU LanguageCode = "KU"
	LO LanguageCode = "LO"
	LA LanguageCode = "LA"
	LI LanguageCode = "LI"
	LN LanguageCode = "LN"
	LU LanguageCode = "LU"
	LB LanguageCode = "LB"
	MK LanguageCode = "MK"
	MG LanguageCode = "MG"
	MS LanguageCode = "MS"
	ML LanguageCode = "ML"
	GV LanguageCode = "GV"
	MI LanguageCode = "MI"
	MR LanguageCode = "MR"
	MH LanguageCode = "MH"
	MN LanguageCode = "MN"
	NA LanguageCode = "NA"
	NV LanguageCode = "NV"
	ND LanguageCode = "ND"
	NR LanguageCode = "NR"
	NG LanguageCode = "NG"
	NE LanguageCode = "NE"
	NB LanguageCode = "NB"
	NN LanguageCode = "NN"
	OC LanguageCode = "OC"
	OJ LanguageCode = "OJ"
	OR LanguageCode = "OR"
	OM LanguageCode = "OM"
	OS LanguageCode = "OS"
	PI LanguageCode = "PI"
	PS LanguageCode = "PS"
	FA LanguageCode = "FA"
	PA LanguageCode = "PA"
	QU LanguageCode = "QU"
	RM LanguageCode = "RM"
	RN LanguageCode = "RN"
	SE LanguageCode = "SE"
	SM LanguageCode = "SM"
	SG LanguageCode = "SG"
	SA LanguageCode = "SA"
	SC LanguageCode = "SC"
	SR LanguageCode = "SR"
	SN LanguageCode = "SN"
	SD LanguageCode = "SD"
	SI LanguageCode = "SI"
	SO LanguageCode = "SO"
	ST LanguageCode = "ST"
	SU LanguageCode = "SU"
	SW LanguageCode = "SW"
	SS LanguageCode = "SS"
	TL LanguageCode = "TL"
	TY LanguageCode = "TY"
	TG LanguageCode = "TG"
	TA LanguageCode = "TA"
	TT LanguageCode = "TT"
	TE LanguageCode = "TE"
	BO LanguageCode = "BO"
	TI LanguageCode = "TI"
	TO LanguageCode = "TO"
	TS LanguageCode = "TS"
	TN LanguageCode = "TN"
	TK LanguageCode = "TK"
	TW LanguageCode = "TW"
	UG LanguageCode = "UG"
	UR LanguageCode = "UR"
	UZ LanguageCode = "UZ"
	VE LanguageCode = "VE"
	VO LanguageCode = "VO"
	WA LanguageCode = "WA"
	CY LanguageCode = "CY"
	WO LanguageCode = "WO"
	XH LanguageCode = "XH"
	II LanguageCode = "II"
	YI LanguageCode = "YI"
	YO LanguageCode = "YO"
	ZA LanguageCode = "ZA"
	ZU LanguageCode = "ZU"
	BB LanguageCode = "BB"
	CB LanguageCode = "CB"
	DB LanguageCode = "DB"
	EB LanguageCode = "EB"
	FB LanguageCode = "FB"
	GB LanguageCode = "GB"
	HB LanguageCode = "HB"
	IB LanguageCode = "IB"
	JB LanguageCode = "JB"
	KB LanguageCode = "KB"
	MB LanguageCode = "MB"
	OB LanguageCode = "OB"
	PB LanguageCode = "PB"
	QB LanguageCode = "QB"
	RB LanguageCode = "RB"
	SB LanguageCode = "SB"
	TB LanguageCode = "TB"
	UB LanguageCode = "UB"
	VB LanguageCode = "VB"
	WB LanguageCode = "WB"
	XB LanguageCode = "XB"
	YB LanguageCode = "YB"
	ZB LanguageCode = "ZB"
)

// All allowed values of LanguageCode enum
var AllowedLanguageCodeEnumValues = []LanguageCode{
	"DE",
	"EN",
	"FR",
	"ES",
	"IT",
	"NL",
	"PL",
	"PT",
	"TR",
	"RU",
	"UK",
	"CS",
	"EL",
	"HU",
	"RO",
	"SV",
	"DA",
	"FI",
	"NO",
	"SK",
	"SL",
	"HR",
	"BG",
	"ET",
	"LV",
	"LT",
	"MT",
	"AR",
	"ZH",
	"JA",
	"KO",
	"TH",
	"VI",
	"ID",
	"HI",
	"AB",
	"AA",
	"AF",
	"AK",
	"SQ",
	"AM",
	"AN",
	"HY",
	"AS",
	"AV",
	"AE",
	"AY",
	"AZ",
	"BM",
	"BA",
	"EU",
	"BE",
	"BN",
	"BI",
	"BS",
	"BR",
	"MY",
	"CA",
	"CH",
	"CE",
	"NY",
	"CU",
	"CV",
	"KW",
	"CO",
	"CR",
	"DV",
	"DZ",
	"EO",
	"EE",
	"FO",
	"FJ",
	"FY",
	"FF",
	"GD",
	"GL",
	"LG",
	"KA",
	"KL",
	"GN",
	"GU",
	"HT",
	"HA",
	"HE",
	"HZ",
	"HO",
	"IS",
	"IO",
	"IG",
	"IA",
	"IE",
	"IU",
	"IK",
	"GA",
	"JV",
	"KN",
	"KR",
	"KS",
	"KK",
	"KM",
	"KI",
	"RW",
	"KY",
	"KV",
	"KG",
	"KJ",
	"KU",
	"LO",
	"LA",
	"LI",
	"LN",
	"LU",
	"LB",
	"MK",
	"MG",
	"MS",
	"ML",
	"GV",
	"MI",
	"MR",
	"MH",
	"MN",
	"NA",
	"NV",
	"ND",
	"NR",
	"NG",
	"NE",
	"NB",
	"NN",
	"OC",
	"OJ",
	"OR",
	"OM",
	"OS",
	"PI",
	"PS",
	"FA",
	"PA",
	"QU",
	"RM",
	"RN",
	"SE",
	"SM",
	"SG",
	"SA",
	"SC",
	"SR",
	"SN",
	"SD",
	"SI",
	"SO",
	"ST",
	"SU",
	"SW",
	"SS",
	"TL",
	"TY",
	"TG",
	"TA",
	"TT",
	"TE",
	"BO",
	"TI",
	"TO",
	"TS",
	"TN",
	"TK",
	"TW",
	"UG",
	"UR",
	"UZ",
	"VE",
	"VO",
	"WA",
	"CY",
	"WO",
	"XH",
	"II",
	"YI",
	"YO",
	"ZA",
	"ZU",
	"BB",
	"CB",
	"DB",
	"EB",
	"FB",
	"GB",
	"HB",
	"IB",
	"JB",
	"KB",
	"MB",
	"OB",
	"PB",
	"QB",
	"RB",
	"SB",
	"TB",
	"UB",
	"VB",
	"WB",
	"XB",
	"YB",
	"ZB",
}

func (v *LanguageCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LanguageCode(value)
	for _, existing := range AllowedLanguageCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LanguageCode", value)
}

// NewLanguageCodeFromValue returns a pointer to a valid LanguageCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLanguageCodeFromValue(v string) (*LanguageCode, error) {
	ev := LanguageCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LanguageCode: valid values are %v", v, AllowedLanguageCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LanguageCode) IsValid() bool {
	for _, existing := range AllowedLanguageCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LanguageCode value
func (v LanguageCode) Ptr() *LanguageCode {
	return &v
}

type NullableLanguageCode struct {
	value *LanguageCode
	isSet bool
}

func (v NullableLanguageCode) Get() *LanguageCode {
	return v.value
}

func (v *NullableLanguageCode) Set(val *LanguageCode) {
	v.value = val
	v.isSet = true
}

func (v NullableLanguageCode) IsSet() bool {
	return v.isSet
}

func (v *NullableLanguageCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanguageCode(val *LanguageCode) *NullableLanguageCode {
	return &NullableLanguageCode{value: val, isSet: true}
}

func (v NullableLanguageCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanguageCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

