/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DatevImportRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatevImportRow{}

// DatevImportRow struct for DatevImportRow
type DatevImportRow struct {
	Account string `json:"account"`
	Amount string `json:"amount"`
	BaseAmount string `json:"base_amount"`
	BaseCurrency string `json:"base_currency"`
	BookingText string `json:"booking_text"`
	BuKey string `json:"bu_key"`
	CostCenter1 string `json:"cost_center1"`
	CostCenter2 string `json:"cost_center2"`
	Currency string `json:"currency"`
	DebitCredit string `json:"debit_credit"`
	Discount string `json:"discount"`
	DocumentDate string `json:"document_date"`
	DocumentField2 string `json:"document_field2"`
	DocumentNumber string `json:"document_number"`
	EuCountryVatId string `json:"eu_country_vat_id"`
	EuTaxRate string `json:"eu_tax_rate"`
	ExchangeRate string `json:"exchange_rate"`
	OppositeAccount string `json:"opposite_account"`
}

type _DatevImportRow DatevImportRow

// NewDatevImportRow instantiates a new DatevImportRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatevImportRow(account string, amount string, baseAmount string, baseCurrency string, bookingText string, buKey string, costCenter1 string, costCenter2 string, currency string, debitCredit string, discount string, documentDate string, documentField2 string, documentNumber string, euCountryVatId string, euTaxRate string, exchangeRate string, oppositeAccount string) *DatevImportRow {
	this := DatevImportRow{}
	this.Account = account
	this.Amount = amount
	this.BaseAmount = baseAmount
	this.BaseCurrency = baseCurrency
	this.BookingText = bookingText
	this.BuKey = buKey
	this.CostCenter1 = costCenter1
	this.CostCenter2 = costCenter2
	this.Currency = currency
	this.DebitCredit = debitCredit
	this.Discount = discount
	this.DocumentDate = documentDate
	this.DocumentField2 = documentField2
	this.DocumentNumber = documentNumber
	this.EuCountryVatId = euCountryVatId
	this.EuTaxRate = euTaxRate
	this.ExchangeRate = exchangeRate
	this.OppositeAccount = oppositeAccount
	return &this
}

// NewDatevImportRowWithDefaults instantiates a new DatevImportRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatevImportRowWithDefaults() *DatevImportRow {
	this := DatevImportRow{}
	return &this
}

// GetAccount returns the Account field value
func (o *DatevImportRow) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *DatevImportRow) SetAccount(v string) {
	o.Account = v
}

// GetAmount returns the Amount field value
func (o *DatevImportRow) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *DatevImportRow) SetAmount(v string) {
	o.Amount = v
}

// GetBaseAmount returns the BaseAmount field value
func (o *DatevImportRow) GetBaseAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseAmount
}

// GetBaseAmountOk returns a tuple with the BaseAmount field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetBaseAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseAmount, true
}

// SetBaseAmount sets field value
func (o *DatevImportRow) SetBaseAmount(v string) {
	o.BaseAmount = v
}

// GetBaseCurrency returns the BaseCurrency field value
func (o *DatevImportRow) GetBaseCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseCurrency
}

// GetBaseCurrencyOk returns a tuple with the BaseCurrency field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetBaseCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseCurrency, true
}

// SetBaseCurrency sets field value
func (o *DatevImportRow) SetBaseCurrency(v string) {
	o.BaseCurrency = v
}

// GetBookingText returns the BookingText field value
func (o *DatevImportRow) GetBookingText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BookingText
}

// GetBookingTextOk returns a tuple with the BookingText field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetBookingTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BookingText, true
}

// SetBookingText sets field value
func (o *DatevImportRow) SetBookingText(v string) {
	o.BookingText = v
}

// GetBuKey returns the BuKey field value
func (o *DatevImportRow) GetBuKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuKey
}

// GetBuKeyOk returns a tuple with the BuKey field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetBuKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuKey, true
}

// SetBuKey sets field value
func (o *DatevImportRow) SetBuKey(v string) {
	o.BuKey = v
}

// GetCostCenter1 returns the CostCenter1 field value
func (o *DatevImportRow) GetCostCenter1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CostCenter1
}

// GetCostCenter1Ok returns a tuple with the CostCenter1 field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetCostCenter1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CostCenter1, true
}

// SetCostCenter1 sets field value
func (o *DatevImportRow) SetCostCenter1(v string) {
	o.CostCenter1 = v
}

// GetCostCenter2 returns the CostCenter2 field value
func (o *DatevImportRow) GetCostCenter2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CostCenter2
}

// GetCostCenter2Ok returns a tuple with the CostCenter2 field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetCostCenter2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CostCenter2, true
}

// SetCostCenter2 sets field value
func (o *DatevImportRow) SetCostCenter2(v string) {
	o.CostCenter2 = v
}

// GetCurrency returns the Currency field value
func (o *DatevImportRow) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *DatevImportRow) SetCurrency(v string) {
	o.Currency = v
}

// GetDebitCredit returns the DebitCredit field value
func (o *DatevImportRow) GetDebitCredit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DebitCredit
}

// GetDebitCreditOk returns a tuple with the DebitCredit field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetDebitCreditOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DebitCredit, true
}

// SetDebitCredit sets field value
func (o *DatevImportRow) SetDebitCredit(v string) {
	o.DebitCredit = v
}

// GetDiscount returns the Discount field value
func (o *DatevImportRow) GetDiscount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetDiscountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Discount, true
}

// SetDiscount sets field value
func (o *DatevImportRow) SetDiscount(v string) {
	o.Discount = v
}

// GetDocumentDate returns the DocumentDate field value
func (o *DatevImportRow) GetDocumentDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentDate
}

// GetDocumentDateOk returns a tuple with the DocumentDate field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetDocumentDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentDate, true
}

// SetDocumentDate sets field value
func (o *DatevImportRow) SetDocumentDate(v string) {
	o.DocumentDate = v
}

// GetDocumentField2 returns the DocumentField2 field value
func (o *DatevImportRow) GetDocumentField2() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentField2
}

// GetDocumentField2Ok returns a tuple with the DocumentField2 field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetDocumentField2Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentField2, true
}

// SetDocumentField2 sets field value
func (o *DatevImportRow) SetDocumentField2(v string) {
	o.DocumentField2 = v
}

// GetDocumentNumber returns the DocumentNumber field value
func (o *DatevImportRow) GetDocumentNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentNumber
}

// GetDocumentNumberOk returns a tuple with the DocumentNumber field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetDocumentNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentNumber, true
}

// SetDocumentNumber sets field value
func (o *DatevImportRow) SetDocumentNumber(v string) {
	o.DocumentNumber = v
}

// GetEuCountryVatId returns the EuCountryVatId field value
func (o *DatevImportRow) GetEuCountryVatId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EuCountryVatId
}

// GetEuCountryVatIdOk returns a tuple with the EuCountryVatId field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetEuCountryVatIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EuCountryVatId, true
}

// SetEuCountryVatId sets field value
func (o *DatevImportRow) SetEuCountryVatId(v string) {
	o.EuCountryVatId = v
}

// GetEuTaxRate returns the EuTaxRate field value
func (o *DatevImportRow) GetEuTaxRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EuTaxRate
}

// GetEuTaxRateOk returns a tuple with the EuTaxRate field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetEuTaxRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EuTaxRate, true
}

// SetEuTaxRate sets field value
func (o *DatevImportRow) SetEuTaxRate(v string) {
	o.EuTaxRate = v
}

// GetExchangeRate returns the ExchangeRate field value
func (o *DatevImportRow) GetExchangeRate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExchangeRate
}

// GetExchangeRateOk returns a tuple with the ExchangeRate field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetExchangeRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExchangeRate, true
}

// SetExchangeRate sets field value
func (o *DatevImportRow) SetExchangeRate(v string) {
	o.ExchangeRate = v
}

// GetOppositeAccount returns the OppositeAccount field value
func (o *DatevImportRow) GetOppositeAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OppositeAccount
}

// GetOppositeAccountOk returns a tuple with the OppositeAccount field value
// and a boolean to check if the value has been set.
func (o *DatevImportRow) GetOppositeAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OppositeAccount, true
}

// SetOppositeAccount sets field value
func (o *DatevImportRow) SetOppositeAccount(v string) {
	o.OppositeAccount = v
}

func (o DatevImportRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatevImportRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["amount"] = o.Amount
	toSerialize["base_amount"] = o.BaseAmount
	toSerialize["base_currency"] = o.BaseCurrency
	toSerialize["booking_text"] = o.BookingText
	toSerialize["bu_key"] = o.BuKey
	toSerialize["cost_center1"] = o.CostCenter1
	toSerialize["cost_center2"] = o.CostCenter2
	toSerialize["currency"] = o.Currency
	toSerialize["debit_credit"] = o.DebitCredit
	toSerialize["discount"] = o.Discount
	toSerialize["document_date"] = o.DocumentDate
	toSerialize["document_field2"] = o.DocumentField2
	toSerialize["document_number"] = o.DocumentNumber
	toSerialize["eu_country_vat_id"] = o.EuCountryVatId
	toSerialize["eu_tax_rate"] = o.EuTaxRate
	toSerialize["exchange_rate"] = o.ExchangeRate
	toSerialize["opposite_account"] = o.OppositeAccount
	return toSerialize, nil
}

func (o *DatevImportRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account",
		"amount",
		"base_amount",
		"base_currency",
		"booking_text",
		"bu_key",
		"cost_center1",
		"cost_center2",
		"currency",
		"debit_credit",
		"discount",
		"document_date",
		"document_field2",
		"document_number",
		"eu_country_vat_id",
		"eu_tax_rate",
		"exchange_rate",
		"opposite_account",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDatevImportRow := _DatevImportRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDatevImportRow)

	if err != nil {
		return err
	}

	*o = DatevImportRow(varDatevImportRow)

	return err
}

type NullableDatevImportRow struct {
	value *DatevImportRow
	isSet bool
}

func (v NullableDatevImportRow) Get() *DatevImportRow {
	return v.value
}

func (v *NullableDatevImportRow) Set(val *DatevImportRow) {
	v.value = val
	v.isSet = true
}

func (v NullableDatevImportRow) IsSet() bool {
	return v.isSet
}

func (v *NullableDatevImportRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatevImportRow(val *DatevImportRow) *NullableDatevImportRow {
	return &NullableDatevImportRow{value: val, isSet: true}
}

func (v NullableDatevImportRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatevImportRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


