/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmitEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmitEventRequest{}

// EmitEventRequest struct for EmitEventRequest
type EmitEventRequest struct {
	EventType string `json:"event_type"`
	Payload interface{} `json:"payload,omitempty"`
}

type _EmitEventRequest EmitEventRequest

// NewEmitEventRequest instantiates a new EmitEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmitEventRequest(eventType string) *EmitEventRequest {
	this := EmitEventRequest{}
	this.EventType = eventType
	return &this
}

// NewEmitEventRequestWithDefaults instantiates a new EmitEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmitEventRequestWithDefaults() *EmitEventRequest {
	this := EmitEventRequest{}
	return &this
}

// GetEventType returns the EventType field value
func (o *EmitEventRequest) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *EmitEventRequest) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *EmitEventRequest) SetEventType(v string) {
	o.EventType = v
}

// GetPayload returns the Payload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmitEventRequest) GetPayload() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmitEventRequest) GetPayloadOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return &o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *EmitEventRequest) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given interface{} and assigns it to the Payload field.
func (o *EmitEventRequest) SetPayload(v interface{}) {
	o.Payload = v
}

func (o EmitEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmitEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_type"] = o.EventType
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

func (o *EmitEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmitEventRequest := _EmitEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmitEventRequest)

	if err != nil {
		return err
	}

	*o = EmitEventRequest(varEmitEventRequest)

	return err
}

type NullableEmitEventRequest struct {
	value *EmitEventRequest
	isSet bool
}

func (v NullableEmitEventRequest) Get() *EmitEventRequest {
	return v.value
}

func (v *NullableEmitEventRequest) Set(val *EmitEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmitEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmitEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmitEventRequest(val *EmitEventRequest) *NullableEmitEventRequest {
	return &NullableEmitEventRequest{value: val, isSet: true}
}

func (v NullableEmitEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmitEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


