/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OffenlegungItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OffenlegungItem{}

// OffenlegungItem struct for OffenlegungItem
type OffenlegungItem struct {
	// Ob die zugrunde liegenden Daten im System vorhanden sind.
	Exists bool `json:"exists"`
	// Bezeichnung des Offenlegungsbestandteils (§ 325 Abs. 1 HGB).
	Name string `json:"name"`
	// Woher der Bestandteil stammt bzw. fehlt.
	Source string `json:"source"`
}

type _OffenlegungItem OffenlegungItem

// NewOffenlegungItem instantiates a new OffenlegungItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOffenlegungItem(exists bool, name string, source string) *OffenlegungItem {
	this := OffenlegungItem{}
	this.Exists = exists
	this.Name = name
	this.Source = source
	return &this
}

// NewOffenlegungItemWithDefaults instantiates a new OffenlegungItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOffenlegungItemWithDefaults() *OffenlegungItem {
	this := OffenlegungItem{}
	return &this
}

// GetExists returns the Exists field value
func (o *OffenlegungItem) GetExists() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Exists
}

// GetExistsOk returns a tuple with the Exists field value
// and a boolean to check if the value has been set.
func (o *OffenlegungItem) GetExistsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exists, true
}

// SetExists sets field value
func (o *OffenlegungItem) SetExists(v bool) {
	o.Exists = v
}

// GetName returns the Name field value
func (o *OffenlegungItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OffenlegungItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OffenlegungItem) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *OffenlegungItem) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *OffenlegungItem) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *OffenlegungItem) SetSource(v string) {
	o.Source = v
}

func (o OffenlegungItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OffenlegungItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exists"] = o.Exists
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *OffenlegungItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exists",
		"name",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOffenlegungItem := _OffenlegungItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOffenlegungItem)

	if err != nil {
		return err
	}

	*o = OffenlegungItem(varOffenlegungItem)

	return err
}

type NullableOffenlegungItem struct {
	value *OffenlegungItem
	isSet bool
}

func (v NullableOffenlegungItem) Get() *OffenlegungItem {
	return v.value
}

func (v *NullableOffenlegungItem) Set(val *OffenlegungItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOffenlegungItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOffenlegungItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOffenlegungItem(val *OffenlegungItem) *NullableOffenlegungItem {
	return &NullableOffenlegungItem{value: val, isSet: true}
}

func (v NullableOffenlegungItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOffenlegungItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


