/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliveryNoteCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryNoteCreate{}

// DeliveryNoteCreate struct for DeliveryNoteCreate
type DeliveryNoteCreate struct {
	Address interface{} `json:"address,omitempty"`
	// References the contact entity.
	ContactId NullableString `json:"contactId,omitempty"`
	ContactName NullableString `json:"contactName,omitempty"`
	Currency string `json:"currency"`
	DeliveryDate NullableString `json:"deliveryDate,omitempty"`
	DeliveryNoteNumber NullableString `json:"deliveryNoteNumber,omitempty"`
	Files interface{} `json:"files,omitempty"`
	Introduction NullableString `json:"introduction,omitempty"`
	LineItems interface{} `json:"lineItems,omitempty"`
	// References the preceding sales voucher entity.
	PrecedingSalesVoucherId NullableString `json:"precedingSalesVoucherId,omitempty"`
	PrecedingSalesVoucherType NullablePrecedingSalesVoucherType `json:"precedingSalesVoucherType,omitempty"`
	Remark NullableString `json:"remark,omitempty"`
	ShippingDate NullableString `json:"shippingDate,omitempty"`
	ShippingMethod NullableString `json:"shippingMethod,omitempty"`
	Title NullableString `json:"title,omitempty"`
	VoucherDate string `json:"voucherDate"`
	VoucherStatus VoucherStatus `json:"voucherStatus"`
}

type _DeliveryNoteCreate DeliveryNoteCreate

// NewDeliveryNoteCreate instantiates a new DeliveryNoteCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryNoteCreate(currency string, voucherDate string, voucherStatus VoucherStatus) *DeliveryNoteCreate {
	this := DeliveryNoteCreate{}
	this.Currency = currency
	this.VoucherDate = voucherDate
	this.VoucherStatus = voucherStatus
	return &this
}

// NewDeliveryNoteCreateWithDefaults instantiates a new DeliveryNoteCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryNoteCreateWithDefaults() *DeliveryNoteCreate {
	this := DeliveryNoteCreate{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetAddress() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetAddressOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return &o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given interface{} and assigns it to the Address field.
func (o *DeliveryNoteCreate) SetAddress(v interface{}) {
	o.Address = v
}

// GetContactId returns the ContactId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetContactId() string {
	if o == nil || IsNil(o.ContactId.Get()) {
		var ret string
		return ret
	}
	return *o.ContactId.Get()
}

// GetContactIdOk returns a tuple with the ContactId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetContactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactId.Get(), o.ContactId.IsSet()
}

// HasContactId returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasContactId() bool {
	if o != nil && o.ContactId.IsSet() {
		return true
	}

	return false
}

// SetContactId gets a reference to the given NullableString and assigns it to the ContactId field.
func (o *DeliveryNoteCreate) SetContactId(v string) {
	o.ContactId.Set(&v)
}
// SetContactIdNil sets the value for ContactId to be an explicit nil
func (o *DeliveryNoteCreate) SetContactIdNil() {
	o.ContactId.Set(nil)
}

// UnsetContactId ensures that no value is present for ContactId, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetContactId() {
	o.ContactId.Unset()
}

// GetContactName returns the ContactName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetContactName() string {
	if o == nil || IsNil(o.ContactName.Get()) {
		var ret string
		return ret
	}
	return *o.ContactName.Get()
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetContactNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactName.Get(), o.ContactName.IsSet()
}

// HasContactName returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasContactName() bool {
	if o != nil && o.ContactName.IsSet() {
		return true
	}

	return false
}

// SetContactName gets a reference to the given NullableString and assigns it to the ContactName field.
func (o *DeliveryNoteCreate) SetContactName(v string) {
	o.ContactName.Set(&v)
}
// SetContactNameNil sets the value for ContactName to be an explicit nil
func (o *DeliveryNoteCreate) SetContactNameNil() {
	o.ContactName.Set(nil)
}

// UnsetContactName ensures that no value is present for ContactName, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetContactName() {
	o.ContactName.Unset()
}

// GetCurrency returns the Currency field value
func (o *DeliveryNoteCreate) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *DeliveryNoteCreate) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *DeliveryNoteCreate) SetCurrency(v string) {
	o.Currency = v
}

// GetDeliveryDate returns the DeliveryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetDeliveryDate() string {
	if o == nil || IsNil(o.DeliveryDate.Get()) {
		var ret string
		return ret
	}
	return *o.DeliveryDate.Get()
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetDeliveryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeliveryDate.Get(), o.DeliveryDate.IsSet()
}

// HasDeliveryDate returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasDeliveryDate() bool {
	if o != nil && o.DeliveryDate.IsSet() {
		return true
	}

	return false
}

// SetDeliveryDate gets a reference to the given NullableString and assigns it to the DeliveryDate field.
func (o *DeliveryNoteCreate) SetDeliveryDate(v string) {
	o.DeliveryDate.Set(&v)
}
// SetDeliveryDateNil sets the value for DeliveryDate to be an explicit nil
func (o *DeliveryNoteCreate) SetDeliveryDateNil() {
	o.DeliveryDate.Set(nil)
}

// UnsetDeliveryDate ensures that no value is present for DeliveryDate, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetDeliveryDate() {
	o.DeliveryDate.Unset()
}

// GetDeliveryNoteNumber returns the DeliveryNoteNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetDeliveryNoteNumber() string {
	if o == nil || IsNil(o.DeliveryNoteNumber.Get()) {
		var ret string
		return ret
	}
	return *o.DeliveryNoteNumber.Get()
}

// GetDeliveryNoteNumberOk returns a tuple with the DeliveryNoteNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetDeliveryNoteNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeliveryNoteNumber.Get(), o.DeliveryNoteNumber.IsSet()
}

// HasDeliveryNoteNumber returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasDeliveryNoteNumber() bool {
	if o != nil && o.DeliveryNoteNumber.IsSet() {
		return true
	}

	return false
}

// SetDeliveryNoteNumber gets a reference to the given NullableString and assigns it to the DeliveryNoteNumber field.
func (o *DeliveryNoteCreate) SetDeliveryNoteNumber(v string) {
	o.DeliveryNoteNumber.Set(&v)
}
// SetDeliveryNoteNumberNil sets the value for DeliveryNoteNumber to be an explicit nil
func (o *DeliveryNoteCreate) SetDeliveryNoteNumberNil() {
	o.DeliveryNoteNumber.Set(nil)
}

// UnsetDeliveryNoteNumber ensures that no value is present for DeliveryNoteNumber, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetDeliveryNoteNumber() {
	o.DeliveryNoteNumber.Unset()
}

// GetFiles returns the Files field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetFiles() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetFilesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return &o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given interface{} and assigns it to the Files field.
func (o *DeliveryNoteCreate) SetFiles(v interface{}) {
	o.Files = v
}

// GetIntroduction returns the Introduction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetIntroduction() string {
	if o == nil || IsNil(o.Introduction.Get()) {
		var ret string
		return ret
	}
	return *o.Introduction.Get()
}

// GetIntroductionOk returns a tuple with the Introduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetIntroductionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Introduction.Get(), o.Introduction.IsSet()
}

// HasIntroduction returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasIntroduction() bool {
	if o != nil && o.Introduction.IsSet() {
		return true
	}

	return false
}

// SetIntroduction gets a reference to the given NullableString and assigns it to the Introduction field.
func (o *DeliveryNoteCreate) SetIntroduction(v string) {
	o.Introduction.Set(&v)
}
// SetIntroductionNil sets the value for Introduction to be an explicit nil
func (o *DeliveryNoteCreate) SetIntroductionNil() {
	o.Introduction.Set(nil)
}

// UnsetIntroduction ensures that no value is present for Introduction, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetIntroduction() {
	o.Introduction.Unset()
}

// GetLineItems returns the LineItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetLineItems() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetLineItemsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return &o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given interface{} and assigns it to the LineItems field.
func (o *DeliveryNoteCreate) SetLineItems(v interface{}) {
	o.LineItems = v
}

// GetPrecedingSalesVoucherId returns the PrecedingSalesVoucherId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetPrecedingSalesVoucherId() string {
	if o == nil || IsNil(o.PrecedingSalesVoucherId.Get()) {
		var ret string
		return ret
	}
	return *o.PrecedingSalesVoucherId.Get()
}

// GetPrecedingSalesVoucherIdOk returns a tuple with the PrecedingSalesVoucherId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetPrecedingSalesVoucherIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrecedingSalesVoucherId.Get(), o.PrecedingSalesVoucherId.IsSet()
}

// HasPrecedingSalesVoucherId returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasPrecedingSalesVoucherId() bool {
	if o != nil && o.PrecedingSalesVoucherId.IsSet() {
		return true
	}

	return false
}

// SetPrecedingSalesVoucherId gets a reference to the given NullableString and assigns it to the PrecedingSalesVoucherId field.
func (o *DeliveryNoteCreate) SetPrecedingSalesVoucherId(v string) {
	o.PrecedingSalesVoucherId.Set(&v)
}
// SetPrecedingSalesVoucherIdNil sets the value for PrecedingSalesVoucherId to be an explicit nil
func (o *DeliveryNoteCreate) SetPrecedingSalesVoucherIdNil() {
	o.PrecedingSalesVoucherId.Set(nil)
}

// UnsetPrecedingSalesVoucherId ensures that no value is present for PrecedingSalesVoucherId, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetPrecedingSalesVoucherId() {
	o.PrecedingSalesVoucherId.Unset()
}

// GetPrecedingSalesVoucherType returns the PrecedingSalesVoucherType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetPrecedingSalesVoucherType() PrecedingSalesVoucherType {
	if o == nil || IsNil(o.PrecedingSalesVoucherType.Get()) {
		var ret PrecedingSalesVoucherType
		return ret
	}
	return *o.PrecedingSalesVoucherType.Get()
}

// GetPrecedingSalesVoucherTypeOk returns a tuple with the PrecedingSalesVoucherType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetPrecedingSalesVoucherTypeOk() (*PrecedingSalesVoucherType, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrecedingSalesVoucherType.Get(), o.PrecedingSalesVoucherType.IsSet()
}

// HasPrecedingSalesVoucherType returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasPrecedingSalesVoucherType() bool {
	if o != nil && o.PrecedingSalesVoucherType.IsSet() {
		return true
	}

	return false
}

// SetPrecedingSalesVoucherType gets a reference to the given NullablePrecedingSalesVoucherType and assigns it to the PrecedingSalesVoucherType field.
func (o *DeliveryNoteCreate) SetPrecedingSalesVoucherType(v PrecedingSalesVoucherType) {
	o.PrecedingSalesVoucherType.Set(&v)
}
// SetPrecedingSalesVoucherTypeNil sets the value for PrecedingSalesVoucherType to be an explicit nil
func (o *DeliveryNoteCreate) SetPrecedingSalesVoucherTypeNil() {
	o.PrecedingSalesVoucherType.Set(nil)
}

// UnsetPrecedingSalesVoucherType ensures that no value is present for PrecedingSalesVoucherType, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetPrecedingSalesVoucherType() {
	o.PrecedingSalesVoucherType.Unset()
}

// GetRemark returns the Remark field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetRemark() string {
	if o == nil || IsNil(o.Remark.Get()) {
		var ret string
		return ret
	}
	return *o.Remark.Get()
}

// GetRemarkOk returns a tuple with the Remark field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetRemarkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Remark.Get(), o.Remark.IsSet()
}

// HasRemark returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasRemark() bool {
	if o != nil && o.Remark.IsSet() {
		return true
	}

	return false
}

// SetRemark gets a reference to the given NullableString and assigns it to the Remark field.
func (o *DeliveryNoteCreate) SetRemark(v string) {
	o.Remark.Set(&v)
}
// SetRemarkNil sets the value for Remark to be an explicit nil
func (o *DeliveryNoteCreate) SetRemarkNil() {
	o.Remark.Set(nil)
}

// UnsetRemark ensures that no value is present for Remark, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetRemark() {
	o.Remark.Unset()
}

// GetShippingDate returns the ShippingDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetShippingDate() string {
	if o == nil || IsNil(o.ShippingDate.Get()) {
		var ret string
		return ret
	}
	return *o.ShippingDate.Get()
}

// GetShippingDateOk returns a tuple with the ShippingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetShippingDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippingDate.Get(), o.ShippingDate.IsSet()
}

// HasShippingDate returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasShippingDate() bool {
	if o != nil && o.ShippingDate.IsSet() {
		return true
	}

	return false
}

// SetShippingDate gets a reference to the given NullableString and assigns it to the ShippingDate field.
func (o *DeliveryNoteCreate) SetShippingDate(v string) {
	o.ShippingDate.Set(&v)
}
// SetShippingDateNil sets the value for ShippingDate to be an explicit nil
func (o *DeliveryNoteCreate) SetShippingDateNil() {
	o.ShippingDate.Set(nil)
}

// UnsetShippingDate ensures that no value is present for ShippingDate, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetShippingDate() {
	o.ShippingDate.Unset()
}

// GetShippingMethod returns the ShippingMethod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetShippingMethod() string {
	if o == nil || IsNil(o.ShippingMethod.Get()) {
		var ret string
		return ret
	}
	return *o.ShippingMethod.Get()
}

// GetShippingMethodOk returns a tuple with the ShippingMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetShippingMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippingMethod.Get(), o.ShippingMethod.IsSet()
}

// HasShippingMethod returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasShippingMethod() bool {
	if o != nil && o.ShippingMethod.IsSet() {
		return true
	}

	return false
}

// SetShippingMethod gets a reference to the given NullableString and assigns it to the ShippingMethod field.
func (o *DeliveryNoteCreate) SetShippingMethod(v string) {
	o.ShippingMethod.Set(&v)
}
// SetShippingMethodNil sets the value for ShippingMethod to be an explicit nil
func (o *DeliveryNoteCreate) SetShippingMethodNil() {
	o.ShippingMethod.Set(nil)
}

// UnsetShippingMethod ensures that no value is present for ShippingMethod, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetShippingMethod() {
	o.ShippingMethod.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryNoteCreate) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryNoteCreate) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *DeliveryNoteCreate) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *DeliveryNoteCreate) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *DeliveryNoteCreate) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *DeliveryNoteCreate) UnsetTitle() {
	o.Title.Unset()
}

// GetVoucherDate returns the VoucherDate field value
func (o *DeliveryNoteCreate) GetVoucherDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VoucherDate
}

// GetVoucherDateOk returns a tuple with the VoucherDate field value
// and a boolean to check if the value has been set.
func (o *DeliveryNoteCreate) GetVoucherDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VoucherDate, true
}

// SetVoucherDate sets field value
func (o *DeliveryNoteCreate) SetVoucherDate(v string) {
	o.VoucherDate = v
}

// GetVoucherStatus returns the VoucherStatus field value
func (o *DeliveryNoteCreate) GetVoucherStatus() VoucherStatus {
	if o == nil {
		var ret VoucherStatus
		return ret
	}

	return o.VoucherStatus
}

// GetVoucherStatusOk returns a tuple with the VoucherStatus field value
// and a boolean to check if the value has been set.
func (o *DeliveryNoteCreate) GetVoucherStatusOk() (*VoucherStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VoucherStatus, true
}

// SetVoucherStatus sets field value
func (o *DeliveryNoteCreate) SetVoucherStatus(v VoucherStatus) {
	o.VoucherStatus = v
}

func (o DeliveryNoteCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryNoteCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.ContactId.IsSet() {
		toSerialize["contactId"] = o.ContactId.Get()
	}
	if o.ContactName.IsSet() {
		toSerialize["contactName"] = o.ContactName.Get()
	}
	toSerialize["currency"] = o.Currency
	if o.DeliveryDate.IsSet() {
		toSerialize["deliveryDate"] = o.DeliveryDate.Get()
	}
	if o.DeliveryNoteNumber.IsSet() {
		toSerialize["deliveryNoteNumber"] = o.DeliveryNoteNumber.Get()
	}
	if o.Files != nil {
		toSerialize["files"] = o.Files
	}
	if o.Introduction.IsSet() {
		toSerialize["introduction"] = o.Introduction.Get()
	}
	if o.LineItems != nil {
		toSerialize["lineItems"] = o.LineItems
	}
	if o.PrecedingSalesVoucherId.IsSet() {
		toSerialize["precedingSalesVoucherId"] = o.PrecedingSalesVoucherId.Get()
	}
	if o.PrecedingSalesVoucherType.IsSet() {
		toSerialize["precedingSalesVoucherType"] = o.PrecedingSalesVoucherType.Get()
	}
	if o.Remark.IsSet() {
		toSerialize["remark"] = o.Remark.Get()
	}
	if o.ShippingDate.IsSet() {
		toSerialize["shippingDate"] = o.ShippingDate.Get()
	}
	if o.ShippingMethod.IsSet() {
		toSerialize["shippingMethod"] = o.ShippingMethod.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	toSerialize["voucherDate"] = o.VoucherDate
	toSerialize["voucherStatus"] = o.VoucherStatus
	return toSerialize, nil
}

func (o *DeliveryNoteCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency",
		"voucherDate",
		"voucherStatus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryNoteCreate := _DeliveryNoteCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryNoteCreate)

	if err != nil {
		return err
	}

	*o = DeliveryNoteCreate(varDeliveryNoteCreate)

	return err
}

type NullableDeliveryNoteCreate struct {
	value *DeliveryNoteCreate
	isSet bool
}

func (v NullableDeliveryNoteCreate) Get() *DeliveryNoteCreate {
	return v.value
}

func (v *NullableDeliveryNoteCreate) Set(val *DeliveryNoteCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryNoteCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryNoteCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryNoteCreate(val *DeliveryNoteCreate) *NullableDeliveryNoteCreate {
	return &NullableDeliveryNoteCreate{value: val, isSet: true}
}

func (v NullableDeliveryNoteCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryNoteCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


