/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PayrollSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayrollSummary{}

// PayrollSummary struct for PayrollSummary
type PayrollSummary struct {
	FirstName string `json:"firstName"`
	HourlyGross NullableString `json:"hourlyGross,omitempty"`
	Id string `json:"id"`
	JobTitle string `json:"jobTitle"`
	LastName string `json:"lastName"`
	MonthlySalary NullableString `json:"monthlySalary,omitempty"`
	Months []PayrollMonth `json:"months"`
	WeeklyHours NullableString `json:"weeklyHours,omitempty"`
	Year int32 `json:"year"`
}

type _PayrollSummary PayrollSummary

// NewPayrollSummary instantiates a new PayrollSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayrollSummary(firstName string, id string, jobTitle string, lastName string, months []PayrollMonth, year int32) *PayrollSummary {
	this := PayrollSummary{}
	this.FirstName = firstName
	this.Id = id
	this.JobTitle = jobTitle
	this.LastName = lastName
	this.Months = months
	this.Year = year
	return &this
}

// NewPayrollSummaryWithDefaults instantiates a new PayrollSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayrollSummaryWithDefaults() *PayrollSummary {
	this := PayrollSummary{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *PayrollSummary) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *PayrollSummary) SetFirstName(v string) {
	o.FirstName = v
}

// GetHourlyGross returns the HourlyGross field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayrollSummary) GetHourlyGross() string {
	if o == nil || IsNil(o.HourlyGross.Get()) {
		var ret string
		return ret
	}
	return *o.HourlyGross.Get()
}

// GetHourlyGrossOk returns a tuple with the HourlyGross field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayrollSummary) GetHourlyGrossOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HourlyGross.Get(), o.HourlyGross.IsSet()
}

// HasHourlyGross returns a boolean if a field has been set.
func (o *PayrollSummary) HasHourlyGross() bool {
	if o != nil && o.HourlyGross.IsSet() {
		return true
	}

	return false
}

// SetHourlyGross gets a reference to the given NullableString and assigns it to the HourlyGross field.
func (o *PayrollSummary) SetHourlyGross(v string) {
	o.HourlyGross.Set(&v)
}
// SetHourlyGrossNil sets the value for HourlyGross to be an explicit nil
func (o *PayrollSummary) SetHourlyGrossNil() {
	o.HourlyGross.Set(nil)
}

// UnsetHourlyGross ensures that no value is present for HourlyGross, not even an explicit nil
func (o *PayrollSummary) UnsetHourlyGross() {
	o.HourlyGross.Unset()
}

// GetId returns the Id field value
func (o *PayrollSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PayrollSummary) SetId(v string) {
	o.Id = v
}

// GetJobTitle returns the JobTitle field value
func (o *PayrollSummary) GetJobTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetJobTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobTitle, true
}

// SetJobTitle sets field value
func (o *PayrollSummary) SetJobTitle(v string) {
	o.JobTitle = v
}

// GetLastName returns the LastName field value
func (o *PayrollSummary) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *PayrollSummary) SetLastName(v string) {
	o.LastName = v
}

// GetMonthlySalary returns the MonthlySalary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayrollSummary) GetMonthlySalary() string {
	if o == nil || IsNil(o.MonthlySalary.Get()) {
		var ret string
		return ret
	}
	return *o.MonthlySalary.Get()
}

// GetMonthlySalaryOk returns a tuple with the MonthlySalary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayrollSummary) GetMonthlySalaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlySalary.Get(), o.MonthlySalary.IsSet()
}

// HasMonthlySalary returns a boolean if a field has been set.
func (o *PayrollSummary) HasMonthlySalary() bool {
	if o != nil && o.MonthlySalary.IsSet() {
		return true
	}

	return false
}

// SetMonthlySalary gets a reference to the given NullableString and assigns it to the MonthlySalary field.
func (o *PayrollSummary) SetMonthlySalary(v string) {
	o.MonthlySalary.Set(&v)
}
// SetMonthlySalaryNil sets the value for MonthlySalary to be an explicit nil
func (o *PayrollSummary) SetMonthlySalaryNil() {
	o.MonthlySalary.Set(nil)
}

// UnsetMonthlySalary ensures that no value is present for MonthlySalary, not even an explicit nil
func (o *PayrollSummary) UnsetMonthlySalary() {
	o.MonthlySalary.Unset()
}

// GetMonths returns the Months field value
func (o *PayrollSummary) GetMonths() []PayrollMonth {
	if o == nil {
		var ret []PayrollMonth
		return ret
	}

	return o.Months
}

// GetMonthsOk returns a tuple with the Months field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetMonthsOk() ([]PayrollMonth, bool) {
	if o == nil {
		return nil, false
	}
	return o.Months, true
}

// SetMonths sets field value
func (o *PayrollSummary) SetMonths(v []PayrollMonth) {
	o.Months = v
}

// GetWeeklyHours returns the WeeklyHours field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PayrollSummary) GetWeeklyHours() string {
	if o == nil || IsNil(o.WeeklyHours.Get()) {
		var ret string
		return ret
	}
	return *o.WeeklyHours.Get()
}

// GetWeeklyHoursOk returns a tuple with the WeeklyHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PayrollSummary) GetWeeklyHoursOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WeeklyHours.Get(), o.WeeklyHours.IsSet()
}

// HasWeeklyHours returns a boolean if a field has been set.
func (o *PayrollSummary) HasWeeklyHours() bool {
	if o != nil && o.WeeklyHours.IsSet() {
		return true
	}

	return false
}

// SetWeeklyHours gets a reference to the given NullableString and assigns it to the WeeklyHours field.
func (o *PayrollSummary) SetWeeklyHours(v string) {
	o.WeeklyHours.Set(&v)
}
// SetWeeklyHoursNil sets the value for WeeklyHours to be an explicit nil
func (o *PayrollSummary) SetWeeklyHoursNil() {
	o.WeeklyHours.Set(nil)
}

// UnsetWeeklyHours ensures that no value is present for WeeklyHours, not even an explicit nil
func (o *PayrollSummary) UnsetWeeklyHours() {
	o.WeeklyHours.Unset()
}

// GetYear returns the Year field value
func (o *PayrollSummary) GetYear() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *PayrollSummary) GetYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *PayrollSummary) SetYear(v int32) {
	o.Year = v
}

func (o PayrollSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayrollSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["firstName"] = o.FirstName
	if o.HourlyGross.IsSet() {
		toSerialize["hourlyGross"] = o.HourlyGross.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["jobTitle"] = o.JobTitle
	toSerialize["lastName"] = o.LastName
	if o.MonthlySalary.IsSet() {
		toSerialize["monthlySalary"] = o.MonthlySalary.Get()
	}
	toSerialize["months"] = o.Months
	if o.WeeklyHours.IsSet() {
		toSerialize["weeklyHours"] = o.WeeklyHours.Get()
	}
	toSerialize["year"] = o.Year
	return toSerialize, nil
}

func (o *PayrollSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"firstName",
		"id",
		"jobTitle",
		"lastName",
		"months",
		"year",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPayrollSummary := _PayrollSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPayrollSummary)

	if err != nil {
		return err
	}

	*o = PayrollSummary(varPayrollSummary)

	return err
}

type NullablePayrollSummary struct {
	value *PayrollSummary
	isSet bool
}

func (v NullablePayrollSummary) Get() *PayrollSummary {
	return v.value
}

func (v *NullablePayrollSummary) Set(val *PayrollSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePayrollSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePayrollSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayrollSummary(val *PayrollSummary) *NullablePayrollSummary {
	return &NullablePayrollSummary{value: val, isSet: true}
}

func (v NullablePayrollSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayrollSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


