/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlatformInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlatformInfo{}

// PlatformInfo Public metadata for one registered plugin (admin UI). Maps 1:1 from [`plugin_core::PluginInfo`] (same field shape as before).
type PlatformInfo struct {
	Author string `json:"author"`
	Changelog []ChangelogEntry `json:"changelog"`
	ConfigFieldNames []string `json:"config_field_names"`
	ConfigFields []ConfigFieldInfo `json:"config_fields"`
	DisplayName string `json:"display_name"`
	Platform string `json:"platform"`
	Pricing PluginPricing `json:"pricing"`
	SupportedEntities []string `json:"supported_entities"`
	SupportsExport bool `json:"supports_export"`
	SupportsImport bool `json:"supports_import"`
	SupportsOauth bool `json:"supports_oauth"`
	Version string `json:"version"`
}

type _PlatformInfo PlatformInfo

// NewPlatformInfo instantiates a new PlatformInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformInfo(author string, changelog []ChangelogEntry, configFieldNames []string, configFields []ConfigFieldInfo, displayName string, platform string, pricing PluginPricing, supportedEntities []string, supportsExport bool, supportsImport bool, supportsOauth bool, version string) *PlatformInfo {
	this := PlatformInfo{}
	this.Author = author
	this.Changelog = changelog
	this.ConfigFieldNames = configFieldNames
	this.ConfigFields = configFields
	this.DisplayName = displayName
	this.Platform = platform
	this.Pricing = pricing
	this.SupportedEntities = supportedEntities
	this.SupportsExport = supportsExport
	this.SupportsImport = supportsImport
	this.SupportsOauth = supportsOauth
	this.Version = version
	return &this
}

// NewPlatformInfoWithDefaults instantiates a new PlatformInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformInfoWithDefaults() *PlatformInfo {
	this := PlatformInfo{}
	return &this
}

// GetAuthor returns the Author field value
func (o *PlatformInfo) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *PlatformInfo) SetAuthor(v string) {
	o.Author = v
}

// GetChangelog returns the Changelog field value
func (o *PlatformInfo) GetChangelog() []ChangelogEntry {
	if o == nil {
		var ret []ChangelogEntry
		return ret
	}

	return o.Changelog
}

// GetChangelogOk returns a tuple with the Changelog field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetChangelogOk() ([]ChangelogEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Changelog, true
}

// SetChangelog sets field value
func (o *PlatformInfo) SetChangelog(v []ChangelogEntry) {
	o.Changelog = v
}

// GetConfigFieldNames returns the ConfigFieldNames field value
func (o *PlatformInfo) GetConfigFieldNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ConfigFieldNames
}

// GetConfigFieldNamesOk returns a tuple with the ConfigFieldNames field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetConfigFieldNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigFieldNames, true
}

// SetConfigFieldNames sets field value
func (o *PlatformInfo) SetConfigFieldNames(v []string) {
	o.ConfigFieldNames = v
}

// GetConfigFields returns the ConfigFields field value
func (o *PlatformInfo) GetConfigFields() []ConfigFieldInfo {
	if o == nil {
		var ret []ConfigFieldInfo
		return ret
	}

	return o.ConfigFields
}

// GetConfigFieldsOk returns a tuple with the ConfigFields field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetConfigFieldsOk() ([]ConfigFieldInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigFields, true
}

// SetConfigFields sets field value
func (o *PlatformInfo) SetConfigFields(v []ConfigFieldInfo) {
	o.ConfigFields = v
}

// GetDisplayName returns the DisplayName field value
func (o *PlatformInfo) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *PlatformInfo) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetPlatform returns the Platform field value
func (o *PlatformInfo) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *PlatformInfo) SetPlatform(v string) {
	o.Platform = v
}

// GetPricing returns the Pricing field value
func (o *PlatformInfo) GetPricing() PluginPricing {
	if o == nil {
		var ret PluginPricing
		return ret
	}

	return o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetPricingOk() (*PluginPricing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pricing, true
}

// SetPricing sets field value
func (o *PlatformInfo) SetPricing(v PluginPricing) {
	o.Pricing = v
}

// GetSupportedEntities returns the SupportedEntities field value
func (o *PlatformInfo) GetSupportedEntities() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SupportedEntities
}

// GetSupportedEntitiesOk returns a tuple with the SupportedEntities field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetSupportedEntitiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedEntities, true
}

// SetSupportedEntities sets field value
func (o *PlatformInfo) SetSupportedEntities(v []string) {
	o.SupportedEntities = v
}

// GetSupportsExport returns the SupportsExport field value
func (o *PlatformInfo) GetSupportsExport() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SupportsExport
}

// GetSupportsExportOk returns a tuple with the SupportsExport field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetSupportsExportOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportsExport, true
}

// SetSupportsExport sets field value
func (o *PlatformInfo) SetSupportsExport(v bool) {
	o.SupportsExport = v
}

// GetSupportsImport returns the SupportsImport field value
func (o *PlatformInfo) GetSupportsImport() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SupportsImport
}

// GetSupportsImportOk returns a tuple with the SupportsImport field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetSupportsImportOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportsImport, true
}

// SetSupportsImport sets field value
func (o *PlatformInfo) SetSupportsImport(v bool) {
	o.SupportsImport = v
}

// GetSupportsOauth returns the SupportsOauth field value
func (o *PlatformInfo) GetSupportsOauth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SupportsOauth
}

// GetSupportsOauthOk returns a tuple with the SupportsOauth field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetSupportsOauthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SupportsOauth, true
}

// SetSupportsOauth sets field value
func (o *PlatformInfo) SetSupportsOauth(v bool) {
	o.SupportsOauth = v
}

// GetVersion returns the Version field value
func (o *PlatformInfo) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PlatformInfo) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PlatformInfo) SetVersion(v string) {
	o.Version = v
}

func (o PlatformInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlatformInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["author"] = o.Author
	toSerialize["changelog"] = o.Changelog
	toSerialize["config_field_names"] = o.ConfigFieldNames
	toSerialize["config_fields"] = o.ConfigFields
	toSerialize["display_name"] = o.DisplayName
	toSerialize["platform"] = o.Platform
	toSerialize["pricing"] = o.Pricing
	toSerialize["supported_entities"] = o.SupportedEntities
	toSerialize["supports_export"] = o.SupportsExport
	toSerialize["supports_import"] = o.SupportsImport
	toSerialize["supports_oauth"] = o.SupportsOauth
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *PlatformInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"author",
		"changelog",
		"config_field_names",
		"config_fields",
		"display_name",
		"platform",
		"pricing",
		"supported_entities",
		"supports_export",
		"supports_import",
		"supports_oauth",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlatformInfo := _PlatformInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlatformInfo)

	if err != nil {
		return err
	}

	*o = PlatformInfo(varPlatformInfo)

	return err
}

type NullablePlatformInfo struct {
	value *PlatformInfo
	isSet bool
}

func (v NullablePlatformInfo) Get() *PlatformInfo {
	return v.value
}

func (v *NullablePlatformInfo) Set(val *PlatformInfo) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformInfo) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformInfo(val *PlatformInfo) *NullablePlatformInfo {
	return &NullablePlatformInfo{value: val, isSet: true}
}

func (v NullablePlatformInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


