/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ReorderProposalResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReorderProposalResponse{}

// ReorderProposalResponse The response envelope for a reorder proposal run.
type ReorderProposalResponse struct {
	GeneratedAt time.Time `json:"generatedAt"`
	Lines []ReorderProposalLine `json:"lines"`
	TotalSuggestedQuantity int64 `json:"totalSuggestedQuantity"`
}

type _ReorderProposalResponse ReorderProposalResponse

// NewReorderProposalResponse instantiates a new ReorderProposalResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReorderProposalResponse(generatedAt time.Time, lines []ReorderProposalLine, totalSuggestedQuantity int64) *ReorderProposalResponse {
	this := ReorderProposalResponse{}
	this.GeneratedAt = generatedAt
	this.Lines = lines
	this.TotalSuggestedQuantity = totalSuggestedQuantity
	return &this
}

// NewReorderProposalResponseWithDefaults instantiates a new ReorderProposalResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReorderProposalResponseWithDefaults() *ReorderProposalResponse {
	this := ReorderProposalResponse{}
	return &this
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *ReorderProposalResponse) GetGeneratedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *ReorderProposalResponse) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *ReorderProposalResponse) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = v
}

// GetLines returns the Lines field value
func (o *ReorderProposalResponse) GetLines() []ReorderProposalLine {
	if o == nil {
		var ret []ReorderProposalLine
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *ReorderProposalResponse) GetLinesOk() ([]ReorderProposalLine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *ReorderProposalResponse) SetLines(v []ReorderProposalLine) {
	o.Lines = v
}

// GetTotalSuggestedQuantity returns the TotalSuggestedQuantity field value
func (o *ReorderProposalResponse) GetTotalSuggestedQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalSuggestedQuantity
}

// GetTotalSuggestedQuantityOk returns a tuple with the TotalSuggestedQuantity field value
// and a boolean to check if the value has been set.
func (o *ReorderProposalResponse) GetTotalSuggestedQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalSuggestedQuantity, true
}

// SetTotalSuggestedQuantity sets field value
func (o *ReorderProposalResponse) SetTotalSuggestedQuantity(v int64) {
	o.TotalSuggestedQuantity = v
}

func (o ReorderProposalResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReorderProposalResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["generatedAt"] = o.GeneratedAt
	toSerialize["lines"] = o.Lines
	toSerialize["totalSuggestedQuantity"] = o.TotalSuggestedQuantity
	return toSerialize, nil
}

func (o *ReorderProposalResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"generatedAt",
		"lines",
		"totalSuggestedQuantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReorderProposalResponse := _ReorderProposalResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReorderProposalResponse)

	if err != nil {
		return err
	}

	*o = ReorderProposalResponse(varReorderProposalResponse)

	return err
}

type NullableReorderProposalResponse struct {
	value *ReorderProposalResponse
	isSet bool
}

func (v NullableReorderProposalResponse) Get() *ReorderProposalResponse {
	return v.value
}

func (v *NullableReorderProposalResponse) Set(val *ReorderProposalResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReorderProposalResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReorderProposalResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReorderProposalResponse(val *ReorderProposalResponse) *NullableReorderProposalResponse {
	return &NullableReorderProposalResponse{value: val, isSet: true}
}

func (v NullableReorderProposalResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReorderProposalResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


