/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpsCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsCredentials{}

// UpsCredentials struct for UpsCredentials
type UpsCredentials struct {
	// OAuth 2.0 client credentials from developer.ups.com.
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	// UPS account number; required for label creation, optional for rates/tracking.
	ShipperNumber NullableString `json:"shipper_number,omitempty"`
}

type _UpsCredentials UpsCredentials

// NewUpsCredentials instantiates a new UpsCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsCredentials(clientId string, clientSecret string) *UpsCredentials {
	this := UpsCredentials{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	return &this
}

// NewUpsCredentialsWithDefaults instantiates a new UpsCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsCredentialsWithDefaults() *UpsCredentials {
	this := UpsCredentials{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *UpsCredentials) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *UpsCredentials) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *UpsCredentials) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *UpsCredentials) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *UpsCredentials) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *UpsCredentials) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetShipperNumber returns the ShipperNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpsCredentials) GetShipperNumber() string {
	if o == nil || IsNil(o.ShipperNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ShipperNumber.Get()
}

// GetShipperNumberOk returns a tuple with the ShipperNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpsCredentials) GetShipperNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShipperNumber.Get(), o.ShipperNumber.IsSet()
}

// HasShipperNumber returns a boolean if a field has been set.
func (o *UpsCredentials) HasShipperNumber() bool {
	if o != nil && o.ShipperNumber.IsSet() {
		return true
	}

	return false
}

// SetShipperNumber gets a reference to the given NullableString and assigns it to the ShipperNumber field.
func (o *UpsCredentials) SetShipperNumber(v string) {
	o.ShipperNumber.Set(&v)
}
// SetShipperNumberNil sets the value for ShipperNumber to be an explicit nil
func (o *UpsCredentials) SetShipperNumberNil() {
	o.ShipperNumber.Set(nil)
}

// UnsetShipperNumber ensures that no value is present for ShipperNumber, not even an explicit nil
func (o *UpsCredentials) UnsetShipperNumber() {
	o.ShipperNumber.Unset()
}

func (o UpsCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	if o.ShipperNumber.IsSet() {
		toSerialize["shipper_number"] = o.ShipperNumber.Get()
	}
	return toSerialize, nil
}

func (o *UpsCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpsCredentials := _UpsCredentials{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpsCredentials)

	if err != nil {
		return err
	}

	*o = UpsCredentials(varUpsCredentials)

	return err
}

type NullableUpsCredentials struct {
	value *UpsCredentials
	isSet bool
}

func (v NullableUpsCredentials) Get() *UpsCredentials {
	return v.value
}

func (v *NullableUpsCredentials) Set(val *UpsCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsCredentials(val *UpsCredentials) *NullableUpsCredentials {
	return &NullableUpsCredentials{value: val, isSet: true}
}

func (v NullableUpsCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


