/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MagicLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagicLinkRequest{}

// MagicLinkRequest struct for MagicLinkRequest
type MagicLinkRequest struct {
	Email string `json:"email"`
}

type _MagicLinkRequest MagicLinkRequest

// NewMagicLinkRequest instantiates a new MagicLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagicLinkRequest(email string) *MagicLinkRequest {
	this := MagicLinkRequest{}
	this.Email = email
	return &this
}

// NewMagicLinkRequestWithDefaults instantiates a new MagicLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagicLinkRequestWithDefaults() *MagicLinkRequest {
	this := MagicLinkRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *MagicLinkRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MagicLinkRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MagicLinkRequest) SetEmail(v string) {
	o.Email = v
}

func (o MagicLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagicLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *MagicLinkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMagicLinkRequest := _MagicLinkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMagicLinkRequest)

	if err != nil {
		return err
	}

	*o = MagicLinkRequest(varMagicLinkRequest)

	return err
}

type NullableMagicLinkRequest struct {
	value *MagicLinkRequest
	isSet bool
}

func (v NullableMagicLinkRequest) Get() *MagicLinkRequest {
	return v.value
}

func (v *NullableMagicLinkRequest) Set(val *MagicLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMagicLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMagicLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagicLinkRequest(val *MagicLinkRequest) *NullableMagicLinkRequest {
	return &NullableMagicLinkRequest{value: val, isSet: true}
}

func (v NullableMagicLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagicLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


