/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UstvaErgebnis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UstvaErgebnis{}

// UstvaErgebnis struct for UstvaErgebnis
type UstvaErgebnis struct {
	Bis string `json:"bis"`
	Hinweis NullableString `json:"hinweis,omitempty"`
	IstKleinunternehmer bool `json:"ist_kleinunternehmer"`
	Kz41 string `json:"kz_41"`
	Kz43 string `json:"kz_43"`
	Kz46 string `json:"kz_46"`
	Kz47 string `json:"kz_47"`
	Kz61 string `json:"kz_61"`
	Kz66 string `json:"kz_66"`
	Kz67 string `json:"kz_67"`
	Kz81 string `json:"kz_81"`
	Kz83 string `json:"kz_83"`
	Kz84 string `json:"kz_84"`
	Kz85 string `json:"kz_85"`
	Kz86 string `json:"kz_86"`
	Kz88 string `json:"kz_88"`
	Kz89 string `json:"kz_89"`
	Kz93 string `json:"kz_93"`
	Von string `json:"von"`
	Zahllast string `json:"zahllast"`
	Zeitraum string `json:"zeitraum"`
	ZeitraumTyp string `json:"zeitraum_typ"`
}

type _UstvaErgebnis UstvaErgebnis

// NewUstvaErgebnis instantiates a new UstvaErgebnis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUstvaErgebnis(bis string, istKleinunternehmer bool, kz41 string, kz43 string, kz46 string, kz47 string, kz61 string, kz66 string, kz67 string, kz81 string, kz83 string, kz84 string, kz85 string, kz86 string, kz88 string, kz89 string, kz93 string, von string, zahllast string, zeitraum string, zeitraumTyp string) *UstvaErgebnis {
	this := UstvaErgebnis{}
	this.Bis = bis
	this.IstKleinunternehmer = istKleinunternehmer
	this.Kz41 = kz41
	this.Kz43 = kz43
	this.Kz46 = kz46
	this.Kz47 = kz47
	this.Kz61 = kz61
	this.Kz66 = kz66
	this.Kz67 = kz67
	this.Kz81 = kz81
	this.Kz83 = kz83
	this.Kz84 = kz84
	this.Kz85 = kz85
	this.Kz86 = kz86
	this.Kz88 = kz88
	this.Kz89 = kz89
	this.Kz93 = kz93
	this.Von = von
	this.Zahllast = zahllast
	this.Zeitraum = zeitraum
	this.ZeitraumTyp = zeitraumTyp
	return &this
}

// NewUstvaErgebnisWithDefaults instantiates a new UstvaErgebnis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUstvaErgebnisWithDefaults() *UstvaErgebnis {
	this := UstvaErgebnis{}
	return &this
}

// GetBis returns the Bis field value
func (o *UstvaErgebnis) GetBis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bis
}

// GetBisOk returns a tuple with the Bis field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetBisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bis, true
}

// SetBis sets field value
func (o *UstvaErgebnis) SetBis(v string) {
	o.Bis = v
}

// GetHinweis returns the Hinweis field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UstvaErgebnis) GetHinweis() string {
	if o == nil || IsNil(o.Hinweis.Get()) {
		var ret string
		return ret
	}
	return *o.Hinweis.Get()
}

// GetHinweisOk returns a tuple with the Hinweis field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UstvaErgebnis) GetHinweisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hinweis.Get(), o.Hinweis.IsSet()
}

// HasHinweis returns a boolean if a field has been set.
func (o *UstvaErgebnis) HasHinweis() bool {
	if o != nil && o.Hinweis.IsSet() {
		return true
	}

	return false
}

// SetHinweis gets a reference to the given NullableString and assigns it to the Hinweis field.
func (o *UstvaErgebnis) SetHinweis(v string) {
	o.Hinweis.Set(&v)
}
// SetHinweisNil sets the value for Hinweis to be an explicit nil
func (o *UstvaErgebnis) SetHinweisNil() {
	o.Hinweis.Set(nil)
}

// UnsetHinweis ensures that no value is present for Hinweis, not even an explicit nil
func (o *UstvaErgebnis) UnsetHinweis() {
	o.Hinweis.Unset()
}

// GetIstKleinunternehmer returns the IstKleinunternehmer field value
func (o *UstvaErgebnis) GetIstKleinunternehmer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IstKleinunternehmer
}

// GetIstKleinunternehmerOk returns a tuple with the IstKleinunternehmer field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetIstKleinunternehmerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IstKleinunternehmer, true
}

// SetIstKleinunternehmer sets field value
func (o *UstvaErgebnis) SetIstKleinunternehmer(v bool) {
	o.IstKleinunternehmer = v
}

// GetKz41 returns the Kz41 field value
func (o *UstvaErgebnis) GetKz41() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz41
}

// GetKz41Ok returns a tuple with the Kz41 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz41Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz41, true
}

// SetKz41 sets field value
func (o *UstvaErgebnis) SetKz41(v string) {
	o.Kz41 = v
}

// GetKz43 returns the Kz43 field value
func (o *UstvaErgebnis) GetKz43() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz43
}

// GetKz43Ok returns a tuple with the Kz43 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz43Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz43, true
}

// SetKz43 sets field value
func (o *UstvaErgebnis) SetKz43(v string) {
	o.Kz43 = v
}

// GetKz46 returns the Kz46 field value
func (o *UstvaErgebnis) GetKz46() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz46
}

// GetKz46Ok returns a tuple with the Kz46 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz46Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz46, true
}

// SetKz46 sets field value
func (o *UstvaErgebnis) SetKz46(v string) {
	o.Kz46 = v
}

// GetKz47 returns the Kz47 field value
func (o *UstvaErgebnis) GetKz47() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz47
}

// GetKz47Ok returns a tuple with the Kz47 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz47Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz47, true
}

// SetKz47 sets field value
func (o *UstvaErgebnis) SetKz47(v string) {
	o.Kz47 = v
}

// GetKz61 returns the Kz61 field value
func (o *UstvaErgebnis) GetKz61() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz61
}

// GetKz61Ok returns a tuple with the Kz61 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz61Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz61, true
}

// SetKz61 sets field value
func (o *UstvaErgebnis) SetKz61(v string) {
	o.Kz61 = v
}

// GetKz66 returns the Kz66 field value
func (o *UstvaErgebnis) GetKz66() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz66
}

// GetKz66Ok returns a tuple with the Kz66 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz66Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz66, true
}

// SetKz66 sets field value
func (o *UstvaErgebnis) SetKz66(v string) {
	o.Kz66 = v
}

// GetKz67 returns the Kz67 field value
func (o *UstvaErgebnis) GetKz67() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz67
}

// GetKz67Ok returns a tuple with the Kz67 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz67Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz67, true
}

// SetKz67 sets field value
func (o *UstvaErgebnis) SetKz67(v string) {
	o.Kz67 = v
}

// GetKz81 returns the Kz81 field value
func (o *UstvaErgebnis) GetKz81() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz81
}

// GetKz81Ok returns a tuple with the Kz81 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz81Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz81, true
}

// SetKz81 sets field value
func (o *UstvaErgebnis) SetKz81(v string) {
	o.Kz81 = v
}

// GetKz83 returns the Kz83 field value
func (o *UstvaErgebnis) GetKz83() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz83
}

// GetKz83Ok returns a tuple with the Kz83 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz83Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz83, true
}

// SetKz83 sets field value
func (o *UstvaErgebnis) SetKz83(v string) {
	o.Kz83 = v
}

// GetKz84 returns the Kz84 field value
func (o *UstvaErgebnis) GetKz84() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz84
}

// GetKz84Ok returns a tuple with the Kz84 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz84Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz84, true
}

// SetKz84 sets field value
func (o *UstvaErgebnis) SetKz84(v string) {
	o.Kz84 = v
}

// GetKz85 returns the Kz85 field value
func (o *UstvaErgebnis) GetKz85() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz85
}

// GetKz85Ok returns a tuple with the Kz85 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz85Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz85, true
}

// SetKz85 sets field value
func (o *UstvaErgebnis) SetKz85(v string) {
	o.Kz85 = v
}

// GetKz86 returns the Kz86 field value
func (o *UstvaErgebnis) GetKz86() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz86
}

// GetKz86Ok returns a tuple with the Kz86 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz86Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz86, true
}

// SetKz86 sets field value
func (o *UstvaErgebnis) SetKz86(v string) {
	o.Kz86 = v
}

// GetKz88 returns the Kz88 field value
func (o *UstvaErgebnis) GetKz88() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz88
}

// GetKz88Ok returns a tuple with the Kz88 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz88Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz88, true
}

// SetKz88 sets field value
func (o *UstvaErgebnis) SetKz88(v string) {
	o.Kz88 = v
}

// GetKz89 returns the Kz89 field value
func (o *UstvaErgebnis) GetKz89() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz89
}

// GetKz89Ok returns a tuple with the Kz89 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz89Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz89, true
}

// SetKz89 sets field value
func (o *UstvaErgebnis) SetKz89(v string) {
	o.Kz89 = v
}

// GetKz93 returns the Kz93 field value
func (o *UstvaErgebnis) GetKz93() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kz93
}

// GetKz93Ok returns a tuple with the Kz93 field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetKz93Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kz93, true
}

// SetKz93 sets field value
func (o *UstvaErgebnis) SetKz93(v string) {
	o.Kz93 = v
}

// GetVon returns the Von field value
func (o *UstvaErgebnis) GetVon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Von
}

// GetVonOk returns a tuple with the Von field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetVonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Von, true
}

// SetVon sets field value
func (o *UstvaErgebnis) SetVon(v string) {
	o.Von = v
}

// GetZahllast returns the Zahllast field value
func (o *UstvaErgebnis) GetZahllast() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zahllast
}

// GetZahllastOk returns a tuple with the Zahllast field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetZahllastOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zahllast, true
}

// SetZahllast sets field value
func (o *UstvaErgebnis) SetZahllast(v string) {
	o.Zahllast = v
}

// GetZeitraum returns the Zeitraum field value
func (o *UstvaErgebnis) GetZeitraum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zeitraum
}

// GetZeitraumOk returns a tuple with the Zeitraum field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetZeitraumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zeitraum, true
}

// SetZeitraum sets field value
func (o *UstvaErgebnis) SetZeitraum(v string) {
	o.Zeitraum = v
}

// GetZeitraumTyp returns the ZeitraumTyp field value
func (o *UstvaErgebnis) GetZeitraumTyp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZeitraumTyp
}

// GetZeitraumTypOk returns a tuple with the ZeitraumTyp field value
// and a boolean to check if the value has been set.
func (o *UstvaErgebnis) GetZeitraumTypOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZeitraumTyp, true
}

// SetZeitraumTyp sets field value
func (o *UstvaErgebnis) SetZeitraumTyp(v string) {
	o.ZeitraumTyp = v
}

func (o UstvaErgebnis) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UstvaErgebnis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bis"] = o.Bis
	if o.Hinweis.IsSet() {
		toSerialize["hinweis"] = o.Hinweis.Get()
	}
	toSerialize["ist_kleinunternehmer"] = o.IstKleinunternehmer
	toSerialize["kz_41"] = o.Kz41
	toSerialize["kz_43"] = o.Kz43
	toSerialize["kz_46"] = o.Kz46
	toSerialize["kz_47"] = o.Kz47
	toSerialize["kz_61"] = o.Kz61
	toSerialize["kz_66"] = o.Kz66
	toSerialize["kz_67"] = o.Kz67
	toSerialize["kz_81"] = o.Kz81
	toSerialize["kz_83"] = o.Kz83
	toSerialize["kz_84"] = o.Kz84
	toSerialize["kz_85"] = o.Kz85
	toSerialize["kz_86"] = o.Kz86
	toSerialize["kz_88"] = o.Kz88
	toSerialize["kz_89"] = o.Kz89
	toSerialize["kz_93"] = o.Kz93
	toSerialize["von"] = o.Von
	toSerialize["zahllast"] = o.Zahllast
	toSerialize["zeitraum"] = o.Zeitraum
	toSerialize["zeitraum_typ"] = o.ZeitraumTyp
	return toSerialize, nil
}

func (o *UstvaErgebnis) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bis",
		"ist_kleinunternehmer",
		"kz_41",
		"kz_43",
		"kz_46",
		"kz_47",
		"kz_61",
		"kz_66",
		"kz_67",
		"kz_81",
		"kz_83",
		"kz_84",
		"kz_85",
		"kz_86",
		"kz_88",
		"kz_89",
		"kz_93",
		"von",
		"zahllast",
		"zeitraum",
		"zeitraum_typ",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUstvaErgebnis := _UstvaErgebnis{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUstvaErgebnis)

	if err != nil {
		return err
	}

	*o = UstvaErgebnis(varUstvaErgebnis)

	return err
}

type NullableUstvaErgebnis struct {
	value *UstvaErgebnis
	isSet bool
}

func (v NullableUstvaErgebnis) Get() *UstvaErgebnis {
	return v.value
}

func (v *NullableUstvaErgebnis) Set(val *UstvaErgebnis) {
	v.value = val
	v.isSet = true
}

func (v NullableUstvaErgebnis) IsSet() bool {
	return v.isSet
}

func (v *NullableUstvaErgebnis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUstvaErgebnis(val *UstvaErgebnis) *NullableUstvaErgebnis {
	return &NullableUstvaErgebnis{value: val, isSet: true}
}

func (v NullableUstvaErgebnis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUstvaErgebnis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


