/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
)

// checks if the TrainingAssignmentCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrainingAssignmentCreate{}

// TrainingAssignmentCreate struct for TrainingAssignmentCreate
type TrainingAssignmentCreate struct {
	AssignedBy NullableString `json:"assignedBy,omitempty"`
	DueDate NullableString `json:"dueDate,omitempty"`
	EmployeeId *string `json:"employeeId,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
	Status *AssignmentStatus `json:"status,omitempty"`
	TrainingId *string `json:"trainingId,omitempty"`
}

// NewTrainingAssignmentCreate instantiates a new TrainingAssignmentCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrainingAssignmentCreate() *TrainingAssignmentCreate {
	this := TrainingAssignmentCreate{}
	return &this
}

// NewTrainingAssignmentCreateWithDefaults instantiates a new TrainingAssignmentCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrainingAssignmentCreateWithDefaults() *TrainingAssignmentCreate {
	this := TrainingAssignmentCreate{}
	return &this
}

// GetAssignedBy returns the AssignedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrainingAssignmentCreate) GetAssignedBy() string {
	if o == nil || IsNil(o.AssignedBy.Get()) {
		var ret string
		return ret
	}
	return *o.AssignedBy.Get()
}

// GetAssignedByOk returns a tuple with the AssignedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrainingAssignmentCreate) GetAssignedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssignedBy.Get(), o.AssignedBy.IsSet()
}

// HasAssignedBy returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasAssignedBy() bool {
	if o != nil && o.AssignedBy.IsSet() {
		return true
	}

	return false
}

// SetAssignedBy gets a reference to the given NullableString and assigns it to the AssignedBy field.
func (o *TrainingAssignmentCreate) SetAssignedBy(v string) {
	o.AssignedBy.Set(&v)
}
// SetAssignedByNil sets the value for AssignedBy to be an explicit nil
func (o *TrainingAssignmentCreate) SetAssignedByNil() {
	o.AssignedBy.Set(nil)
}

// UnsetAssignedBy ensures that no value is present for AssignedBy, not even an explicit nil
func (o *TrainingAssignmentCreate) UnsetAssignedBy() {
	o.AssignedBy.Unset()
}

// GetDueDate returns the DueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrainingAssignmentCreate) GetDueDate() string {
	if o == nil || IsNil(o.DueDate.Get()) {
		var ret string
		return ret
	}
	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrainingAssignmentCreate) GetDueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// HasDueDate returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasDueDate() bool {
	if o != nil && o.DueDate.IsSet() {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given NullableString and assigns it to the DueDate field.
func (o *TrainingAssignmentCreate) SetDueDate(v string) {
	o.DueDate.Set(&v)
}
// SetDueDateNil sets the value for DueDate to be an explicit nil
func (o *TrainingAssignmentCreate) SetDueDateNil() {
	o.DueDate.Set(nil)
}

// UnsetDueDate ensures that no value is present for DueDate, not even an explicit nil
func (o *TrainingAssignmentCreate) UnsetDueDate() {
	o.DueDate.Unset()
}

// GetEmployeeId returns the EmployeeId field value if set, zero value otherwise.
func (o *TrainingAssignmentCreate) GetEmployeeId() string {
	if o == nil || IsNil(o.EmployeeId) {
		var ret string
		return ret
	}
	return *o.EmployeeId
}

// GetEmployeeIdOk returns a tuple with the EmployeeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrainingAssignmentCreate) GetEmployeeIdOk() (*string, bool) {
	if o == nil || IsNil(o.EmployeeId) {
		return nil, false
	}
	return o.EmployeeId, true
}

// HasEmployeeId returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasEmployeeId() bool {
	if o != nil && !IsNil(o.EmployeeId) {
		return true
	}

	return false
}

// SetEmployeeId gets a reference to the given string and assigns it to the EmployeeId field.
func (o *TrainingAssignmentCreate) SetEmployeeId(v string) {
	o.EmployeeId = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrainingAssignmentCreate) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrainingAssignmentCreate) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *TrainingAssignmentCreate) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *TrainingAssignmentCreate) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *TrainingAssignmentCreate) UnsetNotes() {
	o.Notes.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TrainingAssignmentCreate) GetStatus() AssignmentStatus {
	if o == nil || IsNil(o.Status) {
		var ret AssignmentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrainingAssignmentCreate) GetStatusOk() (*AssignmentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given AssignmentStatus and assigns it to the Status field.
func (o *TrainingAssignmentCreate) SetStatus(v AssignmentStatus) {
	o.Status = &v
}

// GetTrainingId returns the TrainingId field value if set, zero value otherwise.
func (o *TrainingAssignmentCreate) GetTrainingId() string {
	if o == nil || IsNil(o.TrainingId) {
		var ret string
		return ret
	}
	return *o.TrainingId
}

// GetTrainingIdOk returns a tuple with the TrainingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrainingAssignmentCreate) GetTrainingIdOk() (*string, bool) {
	if o == nil || IsNil(o.TrainingId) {
		return nil, false
	}
	return o.TrainingId, true
}

// HasTrainingId returns a boolean if a field has been set.
func (o *TrainingAssignmentCreate) HasTrainingId() bool {
	if o != nil && !IsNil(o.TrainingId) {
		return true
	}

	return false
}

// SetTrainingId gets a reference to the given string and assigns it to the TrainingId field.
func (o *TrainingAssignmentCreate) SetTrainingId(v string) {
	o.TrainingId = &v
}

func (o TrainingAssignmentCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrainingAssignmentCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AssignedBy.IsSet() {
		toSerialize["assignedBy"] = o.AssignedBy.Get()
	}
	if o.DueDate.IsSet() {
		toSerialize["dueDate"] = o.DueDate.Get()
	}
	if !IsNil(o.EmployeeId) {
		toSerialize["employeeId"] = o.EmployeeId
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TrainingId) {
		toSerialize["trainingId"] = o.TrainingId
	}
	return toSerialize, nil
}

type NullableTrainingAssignmentCreate struct {
	value *TrainingAssignmentCreate
	isSet bool
}

func (v NullableTrainingAssignmentCreate) Get() *TrainingAssignmentCreate {
	return v.value
}

func (v *NullableTrainingAssignmentCreate) Set(val *TrainingAssignmentCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableTrainingAssignmentCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableTrainingAssignmentCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrainingAssignmentCreate(val *TrainingAssignmentCreate) *NullableTrainingAssignmentCreate {
	return &NullableTrainingAssignmentCreate{value: val, isSet: true}
}

func (v NullableTrainingAssignmentCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrainingAssignmentCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


