/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"fmt"
)

// ReferenceType Stock movement reference type.
type ReferenceType string

// List of ReferenceType
const (
	GOODS_RECEIPT ReferenceType = "goods_receipt"
	PRODUCTION_ORDER ReferenceType = "production_order"
	TRANSFER_IN ReferenceType = "transfer_in"
	STOCK_TRANSFER ReferenceType = "stock_transfer"
	RETURN_ORDER ReferenceType = "return_order"
	INVENTORY_COUNT ReferenceType = "inventory_count"
)

// All allowed values of ReferenceType enum
var AllowedReferenceTypeEnumValues = []ReferenceType{
	"goods_receipt",
	"production_order",
	"transfer_in",
	"stock_transfer",
	"return_order",
	"inventory_count",
}

func (v *ReferenceType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReferenceType(value)
	for _, existing := range AllowedReferenceTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ReferenceType", value)
}

// NewReferenceTypeFromValue returns a pointer to a valid ReferenceType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReferenceTypeFromValue(v string) (*ReferenceType, error) {
	ev := ReferenceType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ReferenceType: valid values are %v", v, AllowedReferenceTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReferenceType) IsValid() bool {
	for _, existing := range AllowedReferenceTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ReferenceType value
func (v ReferenceType) Ptr() *ReferenceType {
	return &v
}

type NullableReferenceType struct {
	value *ReferenceType
	isSet bool
}

func (v NullableReferenceType) Get() *ReferenceType {
	return v.value
}

func (v *NullableReferenceType) Set(val *ReferenceType) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceType) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceType(val *ReferenceType) *NullableReferenceType {
	return &NullableReferenceType{value: val, isSet: true}
}

func (v NullableReferenceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

