/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiResponseSubscriptionOverviewData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseSubscriptionOverviewData{}

// ApiResponseSubscriptionOverviewData Tenant subscription overview for the billing page: current plan, status, period end, trial state, effective limits, current usage and feature flags. Backed by Paddle Billing webhook data written into `billing_info` + `tenants.plan`, and by the canonical plans in `crate::saasy::plans`.  JSON contract (camelCase, matches the frontend): `plan`, `planName`, `priceEur`, `status`, `currentPeriodEnd`, `manageUrl`, `trialEndsAt`, `isTrialing`, `limits:{maxUsers,maxInvoicesPerMonth,maxConnectors}`, `usage:{users,invoicesThisMonth,connectors,overageSeats}`, `features:{taxAutomations,fancyReports,erp}`.
type ApiResponseSubscriptionOverviewData struct {
	CurrentPeriodEnd NullableTime `json:"currentPeriodEnd,omitempty"`
	Features PlanFeatures `json:"features"`
	IsTrialing bool `json:"isTrialing"`
	Limits PlanLimits `json:"limits"`
	ManageUrl NullableString `json:"manageUrl,omitempty"`
	// Resolved plan id (free/starter/business/enterprise, or a custom override id).
	Plan string `json:"plan"`
	PlanName string `json:"planName"`
	// Monthly price in EUR; `-1.0` = custom pricing (enterprise).
	PriceEur float64 `json:"priceEur"`
	Quantity NullableInt32 `json:"quantity,omitempty"`
	Status NullableString `json:"status,omitempty"`
	SubscriptionId NullableString `json:"subscriptionId,omitempty"`
	TrialEndsAt NullableTime `json:"trialEndsAt,omitempty"`
	Usage UsageSnapshot `json:"usage"`
}

type _ApiResponseSubscriptionOverviewData ApiResponseSubscriptionOverviewData

// NewApiResponseSubscriptionOverviewData instantiates a new ApiResponseSubscriptionOverviewData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseSubscriptionOverviewData(features PlanFeatures, isTrialing bool, limits PlanLimits, plan string, planName string, priceEur float64, usage UsageSnapshot) *ApiResponseSubscriptionOverviewData {
	this := ApiResponseSubscriptionOverviewData{}
	this.Features = features
	this.IsTrialing = isTrialing
	this.Limits = limits
	this.Plan = plan
	this.PlanName = planName
	this.PriceEur = priceEur
	this.Usage = usage
	return &this
}

// NewApiResponseSubscriptionOverviewDataWithDefaults instantiates a new ApiResponseSubscriptionOverviewData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseSubscriptionOverviewDataWithDefaults() *ApiResponseSubscriptionOverviewData {
	this := ApiResponseSubscriptionOverviewData{}
	return &this
}

// GetCurrentPeriodEnd returns the CurrentPeriodEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetCurrentPeriodEnd() time.Time {
	if o == nil || IsNil(o.CurrentPeriodEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CurrentPeriodEnd.Get()
}

// GetCurrentPeriodEndOk returns a tuple with the CurrentPeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetCurrentPeriodEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentPeriodEnd.Get(), o.CurrentPeriodEnd.IsSet()
}

// HasCurrentPeriodEnd returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasCurrentPeriodEnd() bool {
	if o != nil && o.CurrentPeriodEnd.IsSet() {
		return true
	}

	return false
}

// SetCurrentPeriodEnd gets a reference to the given NullableTime and assigns it to the CurrentPeriodEnd field.
func (o *ApiResponseSubscriptionOverviewData) SetCurrentPeriodEnd(v time.Time) {
	o.CurrentPeriodEnd.Set(&v)
}
// SetCurrentPeriodEndNil sets the value for CurrentPeriodEnd to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetCurrentPeriodEndNil() {
	o.CurrentPeriodEnd.Set(nil)
}

// UnsetCurrentPeriodEnd ensures that no value is present for CurrentPeriodEnd, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetCurrentPeriodEnd() {
	o.CurrentPeriodEnd.Unset()
}

// GetFeatures returns the Features field value
func (o *ApiResponseSubscriptionOverviewData) GetFeatures() PlanFeatures {
	if o == nil {
		var ret PlanFeatures
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetFeaturesOk() (*PlanFeatures, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *ApiResponseSubscriptionOverviewData) SetFeatures(v PlanFeatures) {
	o.Features = v
}

// GetIsTrialing returns the IsTrialing field value
func (o *ApiResponseSubscriptionOverviewData) GetIsTrialing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTrialing
}

// GetIsTrialingOk returns a tuple with the IsTrialing field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetIsTrialingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTrialing, true
}

// SetIsTrialing sets field value
func (o *ApiResponseSubscriptionOverviewData) SetIsTrialing(v bool) {
	o.IsTrialing = v
}

// GetLimits returns the Limits field value
func (o *ApiResponseSubscriptionOverviewData) GetLimits() PlanLimits {
	if o == nil {
		var ret PlanLimits
		return ret
	}

	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetLimitsOk() (*PlanLimits, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limits, true
}

// SetLimits sets field value
func (o *ApiResponseSubscriptionOverviewData) SetLimits(v PlanLimits) {
	o.Limits = v
}

// GetManageUrl returns the ManageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetManageUrl() string {
	if o == nil || IsNil(o.ManageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ManageUrl.Get()
}

// GetManageUrlOk returns a tuple with the ManageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetManageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManageUrl.Get(), o.ManageUrl.IsSet()
}

// HasManageUrl returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasManageUrl() bool {
	if o != nil && o.ManageUrl.IsSet() {
		return true
	}

	return false
}

// SetManageUrl gets a reference to the given NullableString and assigns it to the ManageUrl field.
func (o *ApiResponseSubscriptionOverviewData) SetManageUrl(v string) {
	o.ManageUrl.Set(&v)
}
// SetManageUrlNil sets the value for ManageUrl to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetManageUrlNil() {
	o.ManageUrl.Set(nil)
}

// UnsetManageUrl ensures that no value is present for ManageUrl, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetManageUrl() {
	o.ManageUrl.Unset()
}

// GetPlan returns the Plan field value
func (o *ApiResponseSubscriptionOverviewData) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *ApiResponseSubscriptionOverviewData) SetPlan(v string) {
	o.Plan = v
}

// GetPlanName returns the PlanName field value
func (o *ApiResponseSubscriptionOverviewData) GetPlanName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanName
}

// GetPlanNameOk returns a tuple with the PlanName field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetPlanNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanName, true
}

// SetPlanName sets field value
func (o *ApiResponseSubscriptionOverviewData) SetPlanName(v string) {
	o.PlanName = v
}

// GetPriceEur returns the PriceEur field value
func (o *ApiResponseSubscriptionOverviewData) GetPriceEur() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.PriceEur
}

// GetPriceEurOk returns a tuple with the PriceEur field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetPriceEurOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceEur, true
}

// SetPriceEur sets field value
func (o *ApiResponseSubscriptionOverviewData) SetPriceEur(v float64) {
	o.PriceEur = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity.Get()) {
		var ret int32
		return ret
	}
	return *o.Quantity.Get()
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quantity.Get(), o.Quantity.IsSet()
}

// HasQuantity returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasQuantity() bool {
	if o != nil && o.Quantity.IsSet() {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given NullableInt32 and assigns it to the Quantity field.
func (o *ApiResponseSubscriptionOverviewData) SetQuantity(v int32) {
	o.Quantity.Set(&v)
}
// SetQuantityNil sets the value for Quantity to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetQuantityNil() {
	o.Quantity.Set(nil)
}

// UnsetQuantity ensures that no value is present for Quantity, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetQuantity() {
	o.Quantity.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *ApiResponseSubscriptionOverviewData) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetStatus() {
	o.Status.Unset()
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId.Get()) {
		var ret string
		return ret
	}
	return *o.SubscriptionId.Get()
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionId.Get(), o.SubscriptionId.IsSet()
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasSubscriptionId() bool {
	if o != nil && o.SubscriptionId.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given NullableString and assigns it to the SubscriptionId field.
func (o *ApiResponseSubscriptionOverviewData) SetSubscriptionId(v string) {
	o.SubscriptionId.Set(&v)
}
// SetSubscriptionIdNil sets the value for SubscriptionId to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetSubscriptionIdNil() {
	o.SubscriptionId.Set(nil)
}

// UnsetSubscriptionId ensures that no value is present for SubscriptionId, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetSubscriptionId() {
	o.SubscriptionId.Unset()
}

// GetTrialEndsAt returns the TrialEndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiResponseSubscriptionOverviewData) GetTrialEndsAt() time.Time {
	if o == nil || IsNil(o.TrialEndsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.TrialEndsAt.Get()
}

// GetTrialEndsAtOk returns a tuple with the TrialEndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiResponseSubscriptionOverviewData) GetTrialEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrialEndsAt.Get(), o.TrialEndsAt.IsSet()
}

// HasTrialEndsAt returns a boolean if a field has been set.
func (o *ApiResponseSubscriptionOverviewData) HasTrialEndsAt() bool {
	if o != nil && o.TrialEndsAt.IsSet() {
		return true
	}

	return false
}

// SetTrialEndsAt gets a reference to the given NullableTime and assigns it to the TrialEndsAt field.
func (o *ApiResponseSubscriptionOverviewData) SetTrialEndsAt(v time.Time) {
	o.TrialEndsAt.Set(&v)
}
// SetTrialEndsAtNil sets the value for TrialEndsAt to be an explicit nil
func (o *ApiResponseSubscriptionOverviewData) SetTrialEndsAtNil() {
	o.TrialEndsAt.Set(nil)
}

// UnsetTrialEndsAt ensures that no value is present for TrialEndsAt, not even an explicit nil
func (o *ApiResponseSubscriptionOverviewData) UnsetTrialEndsAt() {
	o.TrialEndsAt.Unset()
}

// GetUsage returns the Usage field value
func (o *ApiResponseSubscriptionOverviewData) GetUsage() UsageSnapshot {
	if o == nil {
		var ret UsageSnapshot
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *ApiResponseSubscriptionOverviewData) GetUsageOk() (*UsageSnapshot, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *ApiResponseSubscriptionOverviewData) SetUsage(v UsageSnapshot) {
	o.Usage = v
}

func (o ApiResponseSubscriptionOverviewData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseSubscriptionOverviewData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CurrentPeriodEnd.IsSet() {
		toSerialize["currentPeriodEnd"] = o.CurrentPeriodEnd.Get()
	}
	toSerialize["features"] = o.Features
	toSerialize["isTrialing"] = o.IsTrialing
	toSerialize["limits"] = o.Limits
	if o.ManageUrl.IsSet() {
		toSerialize["manageUrl"] = o.ManageUrl.Get()
	}
	toSerialize["plan"] = o.Plan
	toSerialize["planName"] = o.PlanName
	toSerialize["priceEur"] = o.PriceEur
	if o.Quantity.IsSet() {
		toSerialize["quantity"] = o.Quantity.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.SubscriptionId.IsSet() {
		toSerialize["subscriptionId"] = o.SubscriptionId.Get()
	}
	if o.TrialEndsAt.IsSet() {
		toSerialize["trialEndsAt"] = o.TrialEndsAt.Get()
	}
	toSerialize["usage"] = o.Usage
	return toSerialize, nil
}

func (o *ApiResponseSubscriptionOverviewData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"features",
		"isTrialing",
		"limits",
		"plan",
		"planName",
		"priceEur",
		"usage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiResponseSubscriptionOverviewData := _ApiResponseSubscriptionOverviewData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiResponseSubscriptionOverviewData)

	if err != nil {
		return err
	}

	*o = ApiResponseSubscriptionOverviewData(varApiResponseSubscriptionOverviewData)

	return err
}

type NullableApiResponseSubscriptionOverviewData struct {
	value *ApiResponseSubscriptionOverviewData
	isSet bool
}

func (v NullableApiResponseSubscriptionOverviewData) Get() *ApiResponseSubscriptionOverviewData {
	return v.value
}

func (v *NullableApiResponseSubscriptionOverviewData) Set(val *ApiResponseSubscriptionOverviewData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseSubscriptionOverviewData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseSubscriptionOverviewData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseSubscriptionOverviewData(val *ApiResponseSubscriptionOverviewData) *NullableApiResponseSubscriptionOverviewData {
	return &NullableApiResponseSubscriptionOverviewData{value: val, isSet: true}
}

func (v NullableApiResponseSubscriptionOverviewData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseSubscriptionOverviewData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


