/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
)

// checks if the DeliveryDateUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryDateUpdate{}

// DeliveryDateUpdate struct for DeliveryDateUpdate
type DeliveryDateUpdate struct {
	// References the customer entity.
	CustomerId NullableString `json:"customerId,omitempty"`
	// Date actually delivered (set on fulfillment).
	FulfilledDate NullableString `json:"fulfilledDate,omitempty"`
	Note NullableString `json:"note,omitempty"`
	// Sales order number (`order.order_number`).
	OrderNumber NullableString `json:"orderNumber,omitempty"`
	// Original date promised before rescheduling.
	OriginalDate NullableString `json:"originalDate,omitempty"`
	// Product line item this date applies to, if per-item. References the product entity.
	ProductId NullableString `json:"productId,omitempty"`
	// Date promised to the customer.
	PromisedDate NullableString `json:"promisedDate,omitempty"`
	// One of: promised | confirmed | rescheduled | fulfilled | late | cancelled
	Status NullableDeliveryDateStatus `json:"status,omitempty"`
}

// NewDeliveryDateUpdate instantiates a new DeliveryDateUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryDateUpdate() *DeliveryDateUpdate {
	this := DeliveryDateUpdate{}
	return &this
}

// NewDeliveryDateUpdateWithDefaults instantiates a new DeliveryDateUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryDateUpdateWithDefaults() *DeliveryDateUpdate {
	this := DeliveryDateUpdate{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerId.Get()
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerId.Get(), o.CustomerId.IsSet()
}

// HasCustomerId returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasCustomerId() bool {
	if o != nil && o.CustomerId.IsSet() {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given NullableString and assigns it to the CustomerId field.
func (o *DeliveryDateUpdate) SetCustomerId(v string) {
	o.CustomerId.Set(&v)
}
// SetCustomerIdNil sets the value for CustomerId to be an explicit nil
func (o *DeliveryDateUpdate) SetCustomerIdNil() {
	o.CustomerId.Set(nil)
}

// UnsetCustomerId ensures that no value is present for CustomerId, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetCustomerId() {
	o.CustomerId.Unset()
}

// GetFulfilledDate returns the FulfilledDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetFulfilledDate() string {
	if o == nil || IsNil(o.FulfilledDate.Get()) {
		var ret string
		return ret
	}
	return *o.FulfilledDate.Get()
}

// GetFulfilledDateOk returns a tuple with the FulfilledDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetFulfilledDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FulfilledDate.Get(), o.FulfilledDate.IsSet()
}

// HasFulfilledDate returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasFulfilledDate() bool {
	if o != nil && o.FulfilledDate.IsSet() {
		return true
	}

	return false
}

// SetFulfilledDate gets a reference to the given NullableString and assigns it to the FulfilledDate field.
func (o *DeliveryDateUpdate) SetFulfilledDate(v string) {
	o.FulfilledDate.Set(&v)
}
// SetFulfilledDateNil sets the value for FulfilledDate to be an explicit nil
func (o *DeliveryDateUpdate) SetFulfilledDateNil() {
	o.FulfilledDate.Set(nil)
}

// UnsetFulfilledDate ensures that no value is present for FulfilledDate, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetFulfilledDate() {
	o.FulfilledDate.Unset()
}

// GetNote returns the Note field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetNote() string {
	if o == nil || IsNil(o.Note.Get()) {
		var ret string
		return ret
	}
	return *o.Note.Get()
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Note.Get(), o.Note.IsSet()
}

// HasNote returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasNote() bool {
	if o != nil && o.Note.IsSet() {
		return true
	}

	return false
}

// SetNote gets a reference to the given NullableString and assigns it to the Note field.
func (o *DeliveryDateUpdate) SetNote(v string) {
	o.Note.Set(&v)
}
// SetNoteNil sets the value for Note to be an explicit nil
func (o *DeliveryDateUpdate) SetNoteNil() {
	o.Note.Set(nil)
}

// UnsetNote ensures that no value is present for Note, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetNote() {
	o.Note.Unset()
}

// GetOrderNumber returns the OrderNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetOrderNumber() string {
	if o == nil || IsNil(o.OrderNumber.Get()) {
		var ret string
		return ret
	}
	return *o.OrderNumber.Get()
}

// GetOrderNumberOk returns a tuple with the OrderNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetOrderNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderNumber.Get(), o.OrderNumber.IsSet()
}

// HasOrderNumber returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasOrderNumber() bool {
	if o != nil && o.OrderNumber.IsSet() {
		return true
	}

	return false
}

// SetOrderNumber gets a reference to the given NullableString and assigns it to the OrderNumber field.
func (o *DeliveryDateUpdate) SetOrderNumber(v string) {
	o.OrderNumber.Set(&v)
}
// SetOrderNumberNil sets the value for OrderNumber to be an explicit nil
func (o *DeliveryDateUpdate) SetOrderNumberNil() {
	o.OrderNumber.Set(nil)
}

// UnsetOrderNumber ensures that no value is present for OrderNumber, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetOrderNumber() {
	o.OrderNumber.Unset()
}

// GetOriginalDate returns the OriginalDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetOriginalDate() string {
	if o == nil || IsNil(o.OriginalDate.Get()) {
		var ret string
		return ret
	}
	return *o.OriginalDate.Get()
}

// GetOriginalDateOk returns a tuple with the OriginalDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetOriginalDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginalDate.Get(), o.OriginalDate.IsSet()
}

// HasOriginalDate returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasOriginalDate() bool {
	if o != nil && o.OriginalDate.IsSet() {
		return true
	}

	return false
}

// SetOriginalDate gets a reference to the given NullableString and assigns it to the OriginalDate field.
func (o *DeliveryDateUpdate) SetOriginalDate(v string) {
	o.OriginalDate.Set(&v)
}
// SetOriginalDateNil sets the value for OriginalDate to be an explicit nil
func (o *DeliveryDateUpdate) SetOriginalDateNil() {
	o.OriginalDate.Set(nil)
}

// UnsetOriginalDate ensures that no value is present for OriginalDate, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetOriginalDate() {
	o.OriginalDate.Unset()
}

// GetProductId returns the ProductId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetProductId() string {
	if o == nil || IsNil(o.ProductId.Get()) {
		var ret string
		return ret
	}
	return *o.ProductId.Get()
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductId.Get(), o.ProductId.IsSet()
}

// HasProductId returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasProductId() bool {
	if o != nil && o.ProductId.IsSet() {
		return true
	}

	return false
}

// SetProductId gets a reference to the given NullableString and assigns it to the ProductId field.
func (o *DeliveryDateUpdate) SetProductId(v string) {
	o.ProductId.Set(&v)
}
// SetProductIdNil sets the value for ProductId to be an explicit nil
func (o *DeliveryDateUpdate) SetProductIdNil() {
	o.ProductId.Set(nil)
}

// UnsetProductId ensures that no value is present for ProductId, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetProductId() {
	o.ProductId.Unset()
}

// GetPromisedDate returns the PromisedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetPromisedDate() string {
	if o == nil || IsNil(o.PromisedDate.Get()) {
		var ret string
		return ret
	}
	return *o.PromisedDate.Get()
}

// GetPromisedDateOk returns a tuple with the PromisedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetPromisedDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromisedDate.Get(), o.PromisedDate.IsSet()
}

// HasPromisedDate returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasPromisedDate() bool {
	if o != nil && o.PromisedDate.IsSet() {
		return true
	}

	return false
}

// SetPromisedDate gets a reference to the given NullableString and assigns it to the PromisedDate field.
func (o *DeliveryDateUpdate) SetPromisedDate(v string) {
	o.PromisedDate.Set(&v)
}
// SetPromisedDateNil sets the value for PromisedDate to be an explicit nil
func (o *DeliveryDateUpdate) SetPromisedDateNil() {
	o.PromisedDate.Set(nil)
}

// UnsetPromisedDate ensures that no value is present for PromisedDate, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetPromisedDate() {
	o.PromisedDate.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeliveryDateUpdate) GetStatus() DeliveryDateStatus {
	if o == nil || IsNil(o.Status.Get()) {
		var ret DeliveryDateStatus
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeliveryDateUpdate) GetStatusOk() (*DeliveryDateStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *DeliveryDateUpdate) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableDeliveryDateStatus and assigns it to the Status field.
func (o *DeliveryDateUpdate) SetStatus(v DeliveryDateStatus) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *DeliveryDateUpdate) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *DeliveryDateUpdate) UnsetStatus() {
	o.Status.Unset()
}

func (o DeliveryDateUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryDateUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CustomerId.IsSet() {
		toSerialize["customerId"] = o.CustomerId.Get()
	}
	if o.FulfilledDate.IsSet() {
		toSerialize["fulfilledDate"] = o.FulfilledDate.Get()
	}
	if o.Note.IsSet() {
		toSerialize["note"] = o.Note.Get()
	}
	if o.OrderNumber.IsSet() {
		toSerialize["orderNumber"] = o.OrderNumber.Get()
	}
	if o.OriginalDate.IsSet() {
		toSerialize["originalDate"] = o.OriginalDate.Get()
	}
	if o.ProductId.IsSet() {
		toSerialize["productId"] = o.ProductId.Get()
	}
	if o.PromisedDate.IsSet() {
		toSerialize["promisedDate"] = o.PromisedDate.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	return toSerialize, nil
}

type NullableDeliveryDateUpdate struct {
	value *DeliveryDateUpdate
	isSet bool
}

func (v NullableDeliveryDateUpdate) Get() *DeliveryDateUpdate {
	return v.value
}

func (v *NullableDeliveryDateUpdate) Set(val *DeliveryDateUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryDateUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryDateUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryDateUpdate(val *DeliveryDateUpdate) *NullableDeliveryDateUpdate {
	return &NullableDeliveryDateUpdate{value: val, isSet: true}
}

func (v NullableDeliveryDateUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryDateUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


