/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EuerErgebnis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EuerErgebnis{}

// EuerErgebnis struct for EuerErgebnis
type EuerErgebnis struct {
	AnlageZugaenge string `json:"anlage_zugaenge"`
	GewinnVerlust string `json:"gewinn_verlust"`
	Jahr int32 `json:"jahr"`
	SummeAusgaben string `json:"summe_ausgaben"`
	SummeEinnahmen string `json:"summe_einnahmen"`
	Zeilen []EuerZeile `json:"zeilen"`
}

type _EuerErgebnis EuerErgebnis

// NewEuerErgebnis instantiates a new EuerErgebnis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEuerErgebnis(anlageZugaenge string, gewinnVerlust string, jahr int32, summeAusgaben string, summeEinnahmen string, zeilen []EuerZeile) *EuerErgebnis {
	this := EuerErgebnis{}
	this.AnlageZugaenge = anlageZugaenge
	this.GewinnVerlust = gewinnVerlust
	this.Jahr = jahr
	this.SummeAusgaben = summeAusgaben
	this.SummeEinnahmen = summeEinnahmen
	this.Zeilen = zeilen
	return &this
}

// NewEuerErgebnisWithDefaults instantiates a new EuerErgebnis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEuerErgebnisWithDefaults() *EuerErgebnis {
	this := EuerErgebnis{}
	return &this
}

// GetAnlageZugaenge returns the AnlageZugaenge field value
func (o *EuerErgebnis) GetAnlageZugaenge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AnlageZugaenge
}

// GetAnlageZugaengeOk returns a tuple with the AnlageZugaenge field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetAnlageZugaengeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnlageZugaenge, true
}

// SetAnlageZugaenge sets field value
func (o *EuerErgebnis) SetAnlageZugaenge(v string) {
	o.AnlageZugaenge = v
}

// GetGewinnVerlust returns the GewinnVerlust field value
func (o *EuerErgebnis) GetGewinnVerlust() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GewinnVerlust
}

// GetGewinnVerlustOk returns a tuple with the GewinnVerlust field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetGewinnVerlustOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GewinnVerlust, true
}

// SetGewinnVerlust sets field value
func (o *EuerErgebnis) SetGewinnVerlust(v string) {
	o.GewinnVerlust = v
}

// GetJahr returns the Jahr field value
func (o *EuerErgebnis) GetJahr() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Jahr
}

// GetJahrOk returns a tuple with the Jahr field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetJahrOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jahr, true
}

// SetJahr sets field value
func (o *EuerErgebnis) SetJahr(v int32) {
	o.Jahr = v
}

// GetSummeAusgaben returns the SummeAusgaben field value
func (o *EuerErgebnis) GetSummeAusgaben() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SummeAusgaben
}

// GetSummeAusgabenOk returns a tuple with the SummeAusgaben field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetSummeAusgabenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SummeAusgaben, true
}

// SetSummeAusgaben sets field value
func (o *EuerErgebnis) SetSummeAusgaben(v string) {
	o.SummeAusgaben = v
}

// GetSummeEinnahmen returns the SummeEinnahmen field value
func (o *EuerErgebnis) GetSummeEinnahmen() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SummeEinnahmen
}

// GetSummeEinnahmenOk returns a tuple with the SummeEinnahmen field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetSummeEinnahmenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SummeEinnahmen, true
}

// SetSummeEinnahmen sets field value
func (o *EuerErgebnis) SetSummeEinnahmen(v string) {
	o.SummeEinnahmen = v
}

// GetZeilen returns the Zeilen field value
func (o *EuerErgebnis) GetZeilen() []EuerZeile {
	if o == nil {
		var ret []EuerZeile
		return ret
	}

	return o.Zeilen
}

// GetZeilenOk returns a tuple with the Zeilen field value
// and a boolean to check if the value has been set.
func (o *EuerErgebnis) GetZeilenOk() ([]EuerZeile, bool) {
	if o == nil {
		return nil, false
	}
	return o.Zeilen, true
}

// SetZeilen sets field value
func (o *EuerErgebnis) SetZeilen(v []EuerZeile) {
	o.Zeilen = v
}

func (o EuerErgebnis) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EuerErgebnis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["anlage_zugaenge"] = o.AnlageZugaenge
	toSerialize["gewinn_verlust"] = o.GewinnVerlust
	toSerialize["jahr"] = o.Jahr
	toSerialize["summe_ausgaben"] = o.SummeAusgaben
	toSerialize["summe_einnahmen"] = o.SummeEinnahmen
	toSerialize["zeilen"] = o.Zeilen
	return toSerialize, nil
}

func (o *EuerErgebnis) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"anlage_zugaenge",
		"gewinn_verlust",
		"jahr",
		"summe_ausgaben",
		"summe_einnahmen",
		"zeilen",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEuerErgebnis := _EuerErgebnis{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEuerErgebnis)

	if err != nil {
		return err
	}

	*o = EuerErgebnis(varEuerErgebnis)

	return err
}

type NullableEuerErgebnis struct {
	value *EuerErgebnis
	isSet bool
}

func (v NullableEuerErgebnis) Get() *EuerErgebnis {
	return v.value
}

func (v *NullableEuerErgebnis) Set(val *EuerErgebnis) {
	v.value = val
	v.isSet = true
}

func (v NullableEuerErgebnis) IsSet() bool {
	return v.isSet
}

func (v *NullableEuerErgebnis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEuerErgebnis(val *EuerErgebnis) *NullableEuerErgebnis {
	return &NullableEuerErgebnis{value: val, isSet: true}
}

func (v NullableEuerErgebnis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEuerErgebnis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


