/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"time"
)

// checks if the PaymentGatewayUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentGatewayUpdate{}

// PaymentGatewayUpdate struct for PaymentGatewayUpdate
type PaymentGatewayUpdate struct {
	Config interface{} `json:"config,omitempty"`
	CreatedAt NullableTime `json:"createdAt,omitempty"`
	DeletedAt NullableTime `json:"deletedAt,omitempty"`
	Enabled NullableBool `json:"enabled,omitempty"`
	GatewayType NullableGatewayType `json:"gatewayType,omitempty"`
	Label NullableString `json:"label,omitempty"`
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
}

// NewPaymentGatewayUpdate instantiates a new PaymentGatewayUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentGatewayUpdate() *PaymentGatewayUpdate {
	this := PaymentGatewayUpdate{}
	return &this
}

// NewPaymentGatewayUpdateWithDefaults instantiates a new PaymentGatewayUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentGatewayUpdateWithDefaults() *PaymentGatewayUpdate {
	this := PaymentGatewayUpdate{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetConfig() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetConfigOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return &o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given interface{} and assigns it to the Config field.
func (o *PaymentGatewayUpdate) SetConfig(v interface{}) {
	o.Config = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *PaymentGatewayUpdate) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *PaymentGatewayUpdate) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *PaymentGatewayUpdate) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *PaymentGatewayUpdate) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *PaymentGatewayUpdate) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}
// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *PaymentGatewayUpdate) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetGatewayType returns the GatewayType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetGatewayType() GatewayType {
	if o == nil || IsNil(o.GatewayType.Get()) {
		var ret GatewayType
		return ret
	}
	return *o.GatewayType.Get()
}

// GetGatewayTypeOk returns a tuple with the GatewayType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetGatewayTypeOk() (*GatewayType, bool) {
	if o == nil {
		return nil, false
	}
	return o.GatewayType.Get(), o.GatewayType.IsSet()
}

// HasGatewayType returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasGatewayType() bool {
	if o != nil && o.GatewayType.IsSet() {
		return true
	}

	return false
}

// SetGatewayType gets a reference to the given NullableGatewayType and assigns it to the GatewayType field.
func (o *PaymentGatewayUpdate) SetGatewayType(v GatewayType) {
	o.GatewayType.Set(&v)
}
// SetGatewayTypeNil sets the value for GatewayType to be an explicit nil
func (o *PaymentGatewayUpdate) SetGatewayTypeNil() {
	o.GatewayType.Set(nil)
}

// UnsetGatewayType ensures that no value is present for GatewayType, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetGatewayType() {
	o.GatewayType.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *PaymentGatewayUpdate) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *PaymentGatewayUpdate) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetLabel() {
	o.Label.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentGatewayUpdate) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentGatewayUpdate) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PaymentGatewayUpdate) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *PaymentGatewayUpdate) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *PaymentGatewayUpdate) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *PaymentGatewayUpdate) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

func (o PaymentGatewayUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentGatewayUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deletedAt"] = o.DeletedAt.Get()
	}
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	if o.GatewayType.IsSet() {
		toSerialize["gatewayType"] = o.GatewayType.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	return toSerialize, nil
}

type NullablePaymentGatewayUpdate struct {
	value *PaymentGatewayUpdate
	isSet bool
}

func (v NullablePaymentGatewayUpdate) Get() *PaymentGatewayUpdate {
	return v.value
}

func (v *NullablePaymentGatewayUpdate) Set(val *PaymentGatewayUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentGatewayUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentGatewayUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentGatewayUpdate(val *PaymentGatewayUpdate) *NullablePaymentGatewayUpdate {
	return &NullablePaymentGatewayUpdate{value: val, isSet: true}
}

func (v NullablePaymentGatewayUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentGatewayUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


