/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ReturnLogisticsQueueItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReturnLogisticsQueueItem{}

// ReturnLogisticsQueueItem One open return awaiting warehouse processing (inbound queue).
type ReturnLogisticsQueueItem struct {
	// Days since creation, oldest first.
	AgeDays int64 `json:"ageDays"`
	CreatedAt time.Time `json:"createdAt"`
	CustomerName NullableString `json:"customerName,omitempty"`
	LineItems interface{} `json:"lineItems"`
	OrderNumber NullableString `json:"orderNumber,omitempty"`
	ReturnNumber string `json:"returnNumber"`
	ReturnOrderId string `json:"returnOrderId"`
	Status string `json:"status"`
	WarehouseId NullableString `json:"warehouseId,omitempty"`
}

type _ReturnLogisticsQueueItem ReturnLogisticsQueueItem

// NewReturnLogisticsQueueItem instantiates a new ReturnLogisticsQueueItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReturnLogisticsQueueItem(ageDays int64, createdAt time.Time, lineItems interface{}, returnNumber string, returnOrderId string, status string) *ReturnLogisticsQueueItem {
	this := ReturnLogisticsQueueItem{}
	this.AgeDays = ageDays
	this.CreatedAt = createdAt
	this.LineItems = lineItems
	this.ReturnNumber = returnNumber
	this.ReturnOrderId = returnOrderId
	this.Status = status
	return &this
}

// NewReturnLogisticsQueueItemWithDefaults instantiates a new ReturnLogisticsQueueItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReturnLogisticsQueueItemWithDefaults() *ReturnLogisticsQueueItem {
	this := ReturnLogisticsQueueItem{}
	return &this
}

// GetAgeDays returns the AgeDays field value
func (o *ReturnLogisticsQueueItem) GetAgeDays() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AgeDays
}

// GetAgeDaysOk returns a tuple with the AgeDays field value
// and a boolean to check if the value has been set.
func (o *ReturnLogisticsQueueItem) GetAgeDaysOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgeDays, true
}

// SetAgeDays sets field value
func (o *ReturnLogisticsQueueItem) SetAgeDays(v int64) {
	o.AgeDays = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ReturnLogisticsQueueItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ReturnLogisticsQueueItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ReturnLogisticsQueueItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReturnLogisticsQueueItem) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName.Get()) {
		var ret string
		return ret
	}
	return *o.CustomerName.Get()
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReturnLogisticsQueueItem) GetCustomerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomerName.Get(), o.CustomerName.IsSet()
}

// HasCustomerName returns a boolean if a field has been set.
func (o *ReturnLogisticsQueueItem) HasCustomerName() bool {
	if o != nil && o.CustomerName.IsSet() {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given NullableString and assigns it to the CustomerName field.
func (o *ReturnLogisticsQueueItem) SetCustomerName(v string) {
	o.CustomerName.Set(&v)
}
// SetCustomerNameNil sets the value for CustomerName to be an explicit nil
func (o *ReturnLogisticsQueueItem) SetCustomerNameNil() {
	o.CustomerName.Set(nil)
}

// UnsetCustomerName ensures that no value is present for CustomerName, not even an explicit nil
func (o *ReturnLogisticsQueueItem) UnsetCustomerName() {
	o.CustomerName.Unset()
}

// GetLineItems returns the LineItems field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ReturnLogisticsQueueItem) GetLineItems() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReturnLogisticsQueueItem) GetLineItemsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return &o.LineItems, true
}

// SetLineItems sets field value
func (o *ReturnLogisticsQueueItem) SetLineItems(v interface{}) {
	o.LineItems = v
}

// GetOrderNumber returns the OrderNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReturnLogisticsQueueItem) GetOrderNumber() string {
	if o == nil || IsNil(o.OrderNumber.Get()) {
		var ret string
		return ret
	}
	return *o.OrderNumber.Get()
}

// GetOrderNumberOk returns a tuple with the OrderNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReturnLogisticsQueueItem) GetOrderNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderNumber.Get(), o.OrderNumber.IsSet()
}

// HasOrderNumber returns a boolean if a field has been set.
func (o *ReturnLogisticsQueueItem) HasOrderNumber() bool {
	if o != nil && o.OrderNumber.IsSet() {
		return true
	}

	return false
}

// SetOrderNumber gets a reference to the given NullableString and assigns it to the OrderNumber field.
func (o *ReturnLogisticsQueueItem) SetOrderNumber(v string) {
	o.OrderNumber.Set(&v)
}
// SetOrderNumberNil sets the value for OrderNumber to be an explicit nil
func (o *ReturnLogisticsQueueItem) SetOrderNumberNil() {
	o.OrderNumber.Set(nil)
}

// UnsetOrderNumber ensures that no value is present for OrderNumber, not even an explicit nil
func (o *ReturnLogisticsQueueItem) UnsetOrderNumber() {
	o.OrderNumber.Unset()
}

// GetReturnNumber returns the ReturnNumber field value
func (o *ReturnLogisticsQueueItem) GetReturnNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnNumber
}

// GetReturnNumberOk returns a tuple with the ReturnNumber field value
// and a boolean to check if the value has been set.
func (o *ReturnLogisticsQueueItem) GetReturnNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnNumber, true
}

// SetReturnNumber sets field value
func (o *ReturnLogisticsQueueItem) SetReturnNumber(v string) {
	o.ReturnNumber = v
}

// GetReturnOrderId returns the ReturnOrderId field value
func (o *ReturnLogisticsQueueItem) GetReturnOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnOrderId
}

// GetReturnOrderIdOk returns a tuple with the ReturnOrderId field value
// and a boolean to check if the value has been set.
func (o *ReturnLogisticsQueueItem) GetReturnOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnOrderId, true
}

// SetReturnOrderId sets field value
func (o *ReturnLogisticsQueueItem) SetReturnOrderId(v string) {
	o.ReturnOrderId = v
}

// GetStatus returns the Status field value
func (o *ReturnLogisticsQueueItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReturnLogisticsQueueItem) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReturnLogisticsQueueItem) SetStatus(v string) {
	o.Status = v
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReturnLogisticsQueueItem) GetWarehouseId() string {
	if o == nil || IsNil(o.WarehouseId.Get()) {
		var ret string
		return ret
	}
	return *o.WarehouseId.Get()
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReturnLogisticsQueueItem) GetWarehouseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarehouseId.Get(), o.WarehouseId.IsSet()
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *ReturnLogisticsQueueItem) HasWarehouseId() bool {
	if o != nil && o.WarehouseId.IsSet() {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given NullableString and assigns it to the WarehouseId field.
func (o *ReturnLogisticsQueueItem) SetWarehouseId(v string) {
	o.WarehouseId.Set(&v)
}
// SetWarehouseIdNil sets the value for WarehouseId to be an explicit nil
func (o *ReturnLogisticsQueueItem) SetWarehouseIdNil() {
	o.WarehouseId.Set(nil)
}

// UnsetWarehouseId ensures that no value is present for WarehouseId, not even an explicit nil
func (o *ReturnLogisticsQueueItem) UnsetWarehouseId() {
	o.WarehouseId.Unset()
}

func (o ReturnLogisticsQueueItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReturnLogisticsQueueItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ageDays"] = o.AgeDays
	toSerialize["createdAt"] = o.CreatedAt
	if o.CustomerName.IsSet() {
		toSerialize["customerName"] = o.CustomerName.Get()
	}
	if o.LineItems != nil {
		toSerialize["lineItems"] = o.LineItems
	}
	if o.OrderNumber.IsSet() {
		toSerialize["orderNumber"] = o.OrderNumber.Get()
	}
	toSerialize["returnNumber"] = o.ReturnNumber
	toSerialize["returnOrderId"] = o.ReturnOrderId
	toSerialize["status"] = o.Status
	if o.WarehouseId.IsSet() {
		toSerialize["warehouseId"] = o.WarehouseId.Get()
	}
	return toSerialize, nil
}

func (o *ReturnLogisticsQueueItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ageDays",
		"createdAt",
		"lineItems",
		"returnNumber",
		"returnOrderId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReturnLogisticsQueueItem := _ReturnLogisticsQueueItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReturnLogisticsQueueItem)

	if err != nil {
		return err
	}

	*o = ReturnLogisticsQueueItem(varReturnLogisticsQueueItem)

	return err
}

type NullableReturnLogisticsQueueItem struct {
	value *ReturnLogisticsQueueItem
	isSet bool
}

func (v NullableReturnLogisticsQueueItem) Get() *ReturnLogisticsQueueItem {
	return v.value
}

func (v *NullableReturnLogisticsQueueItem) Set(val *ReturnLogisticsQueueItem) {
	v.value = val
	v.isSet = true
}

func (v NullableReturnLogisticsQueueItem) IsSet() bool {
	return v.isSet
}

func (v *NullableReturnLogisticsQueueItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReturnLogisticsQueueItem(val *ReturnLogisticsQueueItem) *NullableReturnLogisticsQueueItem {
	return &NullableReturnLogisticsQueueItem{value: val, isSet: true}
}

func (v NullableReturnLogisticsQueueItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReturnLogisticsQueueItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


