/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"fmt"
)

// AssignmentStatus the model 'AssignmentStatus'
type AssignmentStatus string

// List of AssignmentStatus
const (
	REQUIRED AssignmentStatus = "required"
	COMPLETED AssignmentStatus = "completed"
	OVERDUE AssignmentStatus = "overdue"
	WAIVED AssignmentStatus = "waived"
)

// All allowed values of AssignmentStatus enum
var AllowedAssignmentStatusEnumValues = []AssignmentStatus{
	"required",
	"completed",
	"overdue",
	"waived",
}

func (v *AssignmentStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AssignmentStatus(value)
	for _, existing := range AllowedAssignmentStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AssignmentStatus", value)
}

// NewAssignmentStatusFromValue returns a pointer to a valid AssignmentStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAssignmentStatusFromValue(v string) (*AssignmentStatus, error) {
	ev := AssignmentStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AssignmentStatus: valid values are %v", v, AllowedAssignmentStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AssignmentStatus) IsValid() bool {
	for _, existing := range AllowedAssignmentStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AssignmentStatus value
func (v AssignmentStatus) Ptr() *AssignmentStatus {
	return &v
}

type NullableAssignmentStatus struct {
	value *AssignmentStatus
	isSet bool
}

func (v NullableAssignmentStatus) Get() *AssignmentStatus {
	return v.value
}

func (v *NullableAssignmentStatus) Set(val *AssignmentStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentStatus(val *AssignmentStatus) *NullableAssignmentStatus {
	return &NullableAssignmentStatus{value: val, isSet: true}
}

func (v NullableAssignmentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

