/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"time"
)

// checks if the EmployeeCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeCreate{}

// EmployeeCreate struct for EmployeeCreate
type EmployeeCreate struct {
	Address NullableString `json:"address,omitempty"`
	// References another employee who covers when this employee is absent.
	BackupEmployeeId NullableString `json:"backupEmployeeId,omitempty"`
	Bic NullableString `json:"bic,omitempty"`
	City NullableString `json:"city,omitempty"`
	Country NullableCountryCode `json:"country,omitempty"`
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// References the department entity.
	DepartmentId *string `json:"departmentId,omitempty"`
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	// Gender for pay-transparency reporting: \"male\", \"female\" or \"diverse\".
	Gender NullableGender `json:"gender,omitempty"`
	HireDate NullableString `json:"hireDate,omitempty"`
	// Hourly cost rate in EUR for labor-cost reporting; when unset the rate is derived from `monthly_salary / (weekly_hours * 4.33)`.
	HourlyCost NullableString `json:"hourlyCost,omitempty"`
	Iban NullableString `json:"iban,omitempty"`
	JobTitle *string `json:"jobTitle,omitempty"`
	LastLogin NullableTime `json:"lastLogin,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	LastUpdated NullableTime `json:"lastUpdated,omitempty"`
	// Gross monthly salary in EUR for pay-transparency reporting.
	MonthlySalary NullableString `json:"monthlySalary,omitempty"`
	Phone NullableString `json:"phone,omitempty" validate:"regexp=^\\+?[0-9\\s\\-\\(\\)]{7\\,20}$"`
	State NullableString `json:"state,omitempty"`
	Status *EmployeeStatus `json:"status,omitempty"`
	// References the user entity.
	UserId NullableString `json:"userId,omitempty"`
	// Contractual weekly working hours for pay-transparency normalization.
	WeeklyHours NullableString `json:"weeklyHours,omitempty"`
	Zip NullableString `json:"zip,omitempty"`
}

// NewEmployeeCreate instantiates a new EmployeeCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeCreate() *EmployeeCreate {
	this := EmployeeCreate{}
	return &this
}

// NewEmployeeCreateWithDefaults instantiates a new EmployeeCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeCreateWithDefaults() *EmployeeCreate {
	this := EmployeeCreate{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *EmployeeCreate) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *EmployeeCreate) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *EmployeeCreate) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *EmployeeCreate) UnsetAddress() {
	o.Address.Unset()
}

// GetBackupEmployeeId returns the BackupEmployeeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetBackupEmployeeId() string {
	if o == nil || IsNil(o.BackupEmployeeId.Get()) {
		var ret string
		return ret
	}
	return *o.BackupEmployeeId.Get()
}

// GetBackupEmployeeIdOk returns a tuple with the BackupEmployeeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetBackupEmployeeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupEmployeeId.Get(), o.BackupEmployeeId.IsSet()
}

// HasBackupEmployeeId returns a boolean if a field has been set.
func (o *EmployeeCreate) HasBackupEmployeeId() bool {
	if o != nil && o.BackupEmployeeId.IsSet() {
		return true
	}

	return false
}

// SetBackupEmployeeId gets a reference to the given NullableString and assigns it to the BackupEmployeeId field.
func (o *EmployeeCreate) SetBackupEmployeeId(v string) {
	o.BackupEmployeeId.Set(&v)
}
// SetBackupEmployeeIdNil sets the value for BackupEmployeeId to be an explicit nil
func (o *EmployeeCreate) SetBackupEmployeeIdNil() {
	o.BackupEmployeeId.Set(nil)
}

// UnsetBackupEmployeeId ensures that no value is present for BackupEmployeeId, not even an explicit nil
func (o *EmployeeCreate) UnsetBackupEmployeeId() {
	o.BackupEmployeeId.Unset()
}

// GetBic returns the Bic field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetBic() string {
	if o == nil || IsNil(o.Bic.Get()) {
		var ret string
		return ret
	}
	return *o.Bic.Get()
}

// GetBicOk returns a tuple with the Bic field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetBicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bic.Get(), o.Bic.IsSet()
}

// HasBic returns a boolean if a field has been set.
func (o *EmployeeCreate) HasBic() bool {
	if o != nil && o.Bic.IsSet() {
		return true
	}

	return false
}

// SetBic gets a reference to the given NullableString and assigns it to the Bic field.
func (o *EmployeeCreate) SetBic(v string) {
	o.Bic.Set(&v)
}
// SetBicNil sets the value for Bic to be an explicit nil
func (o *EmployeeCreate) SetBicNil() {
	o.Bic.Set(nil)
}

// UnsetBic ensures that no value is present for Bic, not even an explicit nil
func (o *EmployeeCreate) UnsetBic() {
	o.Bic.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *EmployeeCreate) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *EmployeeCreate) SetCity(v string) {
	o.City.Set(&v)
}
// SetCityNil sets the value for City to be an explicit nil
func (o *EmployeeCreate) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *EmployeeCreate) UnsetCity() {
	o.City.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetCountry() CountryCode {
	if o == nil || IsNil(o.Country.Get()) {
		var ret CountryCode
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetCountryOk() (*CountryCode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *EmployeeCreate) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableCountryCode and assigns it to the Country field.
func (o *EmployeeCreate) SetCountry(v CountryCode) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *EmployeeCreate) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *EmployeeCreate) UnsetCountry() {
	o.Country.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *EmployeeCreate) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *EmployeeCreate) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *EmployeeCreate) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *EmployeeCreate) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetDepartmentId returns the DepartmentId field value if set, zero value otherwise.
func (o *EmployeeCreate) GetDepartmentId() string {
	if o == nil || IsNil(o.DepartmentId) {
		var ret string
		return ret
	}
	return *o.DepartmentId
}

// GetDepartmentIdOk returns a tuple with the DepartmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetDepartmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DepartmentId) {
		return nil, false
	}
	return o.DepartmentId, true
}

// HasDepartmentId returns a boolean if a field has been set.
func (o *EmployeeCreate) HasDepartmentId() bool {
	if o != nil && !IsNil(o.DepartmentId) {
		return true
	}

	return false
}

// SetDepartmentId gets a reference to the given string and assigns it to the DepartmentId field.
func (o *EmployeeCreate) SetDepartmentId(v string) {
	o.DepartmentId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *EmployeeCreate) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *EmployeeCreate) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *EmployeeCreate) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *EmployeeCreate) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *EmployeeCreate) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *EmployeeCreate) SetFirstName(v string) {
	o.FirstName = &v
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetGender() Gender {
	if o == nil || IsNil(o.Gender.Get()) {
		var ret Gender
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetGenderOk() (*Gender, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *EmployeeCreate) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableGender and assigns it to the Gender field.
func (o *EmployeeCreate) SetGender(v Gender) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *EmployeeCreate) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *EmployeeCreate) UnsetGender() {
	o.Gender.Unset()
}

// GetHireDate returns the HireDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetHireDate() string {
	if o == nil || IsNil(o.HireDate.Get()) {
		var ret string
		return ret
	}
	return *o.HireDate.Get()
}

// GetHireDateOk returns a tuple with the HireDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetHireDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HireDate.Get(), o.HireDate.IsSet()
}

// HasHireDate returns a boolean if a field has been set.
func (o *EmployeeCreate) HasHireDate() bool {
	if o != nil && o.HireDate.IsSet() {
		return true
	}

	return false
}

// SetHireDate gets a reference to the given NullableString and assigns it to the HireDate field.
func (o *EmployeeCreate) SetHireDate(v string) {
	o.HireDate.Set(&v)
}
// SetHireDateNil sets the value for HireDate to be an explicit nil
func (o *EmployeeCreate) SetHireDateNil() {
	o.HireDate.Set(nil)
}

// UnsetHireDate ensures that no value is present for HireDate, not even an explicit nil
func (o *EmployeeCreate) UnsetHireDate() {
	o.HireDate.Unset()
}

// GetHourlyCost returns the HourlyCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetHourlyCost() string {
	if o == nil || IsNil(o.HourlyCost.Get()) {
		var ret string
		return ret
	}
	return *o.HourlyCost.Get()
}

// GetHourlyCostOk returns a tuple with the HourlyCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetHourlyCostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HourlyCost.Get(), o.HourlyCost.IsSet()
}

// HasHourlyCost returns a boolean if a field has been set.
func (o *EmployeeCreate) HasHourlyCost() bool {
	if o != nil && o.HourlyCost.IsSet() {
		return true
	}

	return false
}

// SetHourlyCost gets a reference to the given NullableString and assigns it to the HourlyCost field.
func (o *EmployeeCreate) SetHourlyCost(v string) {
	o.HourlyCost.Set(&v)
}
// SetHourlyCostNil sets the value for HourlyCost to be an explicit nil
func (o *EmployeeCreate) SetHourlyCostNil() {
	o.HourlyCost.Set(nil)
}

// UnsetHourlyCost ensures that no value is present for HourlyCost, not even an explicit nil
func (o *EmployeeCreate) UnsetHourlyCost() {
	o.HourlyCost.Unset()
}

// GetIban returns the Iban field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetIban() string {
	if o == nil || IsNil(o.Iban.Get()) {
		var ret string
		return ret
	}
	return *o.Iban.Get()
}

// GetIbanOk returns a tuple with the Iban field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetIbanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Iban.Get(), o.Iban.IsSet()
}

// HasIban returns a boolean if a field has been set.
func (o *EmployeeCreate) HasIban() bool {
	if o != nil && o.Iban.IsSet() {
		return true
	}

	return false
}

// SetIban gets a reference to the given NullableString and assigns it to the Iban field.
func (o *EmployeeCreate) SetIban(v string) {
	o.Iban.Set(&v)
}
// SetIbanNil sets the value for Iban to be an explicit nil
func (o *EmployeeCreate) SetIbanNil() {
	o.Iban.Set(nil)
}

// UnsetIban ensures that no value is present for Iban, not even an explicit nil
func (o *EmployeeCreate) UnsetIban() {
	o.Iban.Unset()
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *EmployeeCreate) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *EmployeeCreate) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *EmployeeCreate) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetLastLogin() time.Time {
	if o == nil || IsNil(o.LastLogin.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastLogin.Get()
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetLastLoginOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastLogin.Get(), o.LastLogin.IsSet()
}

// HasLastLogin returns a boolean if a field has been set.
func (o *EmployeeCreate) HasLastLogin() bool {
	if o != nil && o.LastLogin.IsSet() {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given NullableTime and assigns it to the LastLogin field.
func (o *EmployeeCreate) SetLastLogin(v time.Time) {
	o.LastLogin.Set(&v)
}
// SetLastLoginNil sets the value for LastLogin to be an explicit nil
func (o *EmployeeCreate) SetLastLoginNil() {
	o.LastLogin.Set(nil)
}

// UnsetLastLogin ensures that no value is present for LastLogin, not even an explicit nil
func (o *EmployeeCreate) UnsetLastLogin() {
	o.LastLogin.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *EmployeeCreate) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *EmployeeCreate) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *EmployeeCreate) SetLastName(v string) {
	o.LastName = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *EmployeeCreate) HasLastUpdated() bool {
	if o != nil && o.LastUpdated.IsSet() {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given NullableTime and assigns it to the LastUpdated field.
func (o *EmployeeCreate) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}
// SetLastUpdatedNil sets the value for LastUpdated to be an explicit nil
func (o *EmployeeCreate) SetLastUpdatedNil() {
	o.LastUpdated.Set(nil)
}

// UnsetLastUpdated ensures that no value is present for LastUpdated, not even an explicit nil
func (o *EmployeeCreate) UnsetLastUpdated() {
	o.LastUpdated.Unset()
}

// GetMonthlySalary returns the MonthlySalary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetMonthlySalary() string {
	if o == nil || IsNil(o.MonthlySalary.Get()) {
		var ret string
		return ret
	}
	return *o.MonthlySalary.Get()
}

// GetMonthlySalaryOk returns a tuple with the MonthlySalary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetMonthlySalaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlySalary.Get(), o.MonthlySalary.IsSet()
}

// HasMonthlySalary returns a boolean if a field has been set.
func (o *EmployeeCreate) HasMonthlySalary() bool {
	if o != nil && o.MonthlySalary.IsSet() {
		return true
	}

	return false
}

// SetMonthlySalary gets a reference to the given NullableString and assigns it to the MonthlySalary field.
func (o *EmployeeCreate) SetMonthlySalary(v string) {
	o.MonthlySalary.Set(&v)
}
// SetMonthlySalaryNil sets the value for MonthlySalary to be an explicit nil
func (o *EmployeeCreate) SetMonthlySalaryNil() {
	o.MonthlySalary.Set(nil)
}

// UnsetMonthlySalary ensures that no value is present for MonthlySalary, not even an explicit nil
func (o *EmployeeCreate) UnsetMonthlySalary() {
	o.MonthlySalary.Unset()
}

// GetPhone returns the Phone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetPhone() string {
	if o == nil || IsNil(o.Phone.Get()) {
		var ret string
		return ret
	}
	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// HasPhone returns a boolean if a field has been set.
func (o *EmployeeCreate) HasPhone() bool {
	if o != nil && o.Phone.IsSet() {
		return true
	}

	return false
}

// SetPhone gets a reference to the given NullableString and assigns it to the Phone field.
func (o *EmployeeCreate) SetPhone(v string) {
	o.Phone.Set(&v)
}
// SetPhoneNil sets the value for Phone to be an explicit nil
func (o *EmployeeCreate) SetPhoneNil() {
	o.Phone.Set(nil)
}

// UnsetPhone ensures that no value is present for Phone, not even an explicit nil
func (o *EmployeeCreate) UnsetPhone() {
	o.Phone.Unset()
}

// GetState returns the State field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetState() string {
	if o == nil || IsNil(o.State.Get()) {
		var ret string
		return ret
	}
	return *o.State.Get()
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.State.Get(), o.State.IsSet()
}

// HasState returns a boolean if a field has been set.
func (o *EmployeeCreate) HasState() bool {
	if o != nil && o.State.IsSet() {
		return true
	}

	return false
}

// SetState gets a reference to the given NullableString and assigns it to the State field.
func (o *EmployeeCreate) SetState(v string) {
	o.State.Set(&v)
}
// SetStateNil sets the value for State to be an explicit nil
func (o *EmployeeCreate) SetStateNil() {
	o.State.Set(nil)
}

// UnsetState ensures that no value is present for State, not even an explicit nil
func (o *EmployeeCreate) UnsetState() {
	o.State.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmployeeCreate) GetStatus() EmployeeStatus {
	if o == nil || IsNil(o.Status) {
		var ret EmployeeStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeCreate) GetStatusOk() (*EmployeeStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmployeeCreate) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EmployeeStatus and assigns it to the Status field.
func (o *EmployeeCreate) SetStatus(v EmployeeStatus) {
	o.Status = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetUserId() string {
	if o == nil || IsNil(o.UserId.Get()) {
		var ret string
		return ret
	}
	return *o.UserId.Get()
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserId.Get(), o.UserId.IsSet()
}

// HasUserId returns a boolean if a field has been set.
func (o *EmployeeCreate) HasUserId() bool {
	if o != nil && o.UserId.IsSet() {
		return true
	}

	return false
}

// SetUserId gets a reference to the given NullableString and assigns it to the UserId field.
func (o *EmployeeCreate) SetUserId(v string) {
	o.UserId.Set(&v)
}
// SetUserIdNil sets the value for UserId to be an explicit nil
func (o *EmployeeCreate) SetUserIdNil() {
	o.UserId.Set(nil)
}

// UnsetUserId ensures that no value is present for UserId, not even an explicit nil
func (o *EmployeeCreate) UnsetUserId() {
	o.UserId.Unset()
}

// GetWeeklyHours returns the WeeklyHours field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetWeeklyHours() string {
	if o == nil || IsNil(o.WeeklyHours.Get()) {
		var ret string
		return ret
	}
	return *o.WeeklyHours.Get()
}

// GetWeeklyHoursOk returns a tuple with the WeeklyHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetWeeklyHoursOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WeeklyHours.Get(), o.WeeklyHours.IsSet()
}

// HasWeeklyHours returns a boolean if a field has been set.
func (o *EmployeeCreate) HasWeeklyHours() bool {
	if o != nil && o.WeeklyHours.IsSet() {
		return true
	}

	return false
}

// SetWeeklyHours gets a reference to the given NullableString and assigns it to the WeeklyHours field.
func (o *EmployeeCreate) SetWeeklyHours(v string) {
	o.WeeklyHours.Set(&v)
}
// SetWeeklyHoursNil sets the value for WeeklyHours to be an explicit nil
func (o *EmployeeCreate) SetWeeklyHoursNil() {
	o.WeeklyHours.Set(nil)
}

// UnsetWeeklyHours ensures that no value is present for WeeklyHours, not even an explicit nil
func (o *EmployeeCreate) UnsetWeeklyHours() {
	o.WeeklyHours.Unset()
}

// GetZip returns the Zip field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmployeeCreate) GetZip() string {
	if o == nil || IsNil(o.Zip.Get()) {
		var ret string
		return ret
	}
	return *o.Zip.Get()
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmployeeCreate) GetZipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Zip.Get(), o.Zip.IsSet()
}

// HasZip returns a boolean if a field has been set.
func (o *EmployeeCreate) HasZip() bool {
	if o != nil && o.Zip.IsSet() {
		return true
	}

	return false
}

// SetZip gets a reference to the given NullableString and assigns it to the Zip field.
func (o *EmployeeCreate) SetZip(v string) {
	o.Zip.Set(&v)
}
// SetZipNil sets the value for Zip to be an explicit nil
func (o *EmployeeCreate) SetZipNil() {
	o.Zip.Set(nil)
}

// UnsetZip ensures that no value is present for Zip, not even an explicit nil
func (o *EmployeeCreate) UnsetZip() {
	o.Zip.Unset()
}

func (o EmployeeCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.BackupEmployeeId.IsSet() {
		toSerialize["backupEmployeeId"] = o.BackupEmployeeId.Get()
	}
	if o.Bic.IsSet() {
		toSerialize["bic"] = o.Bic.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if !IsNil(o.DepartmentId) {
		toSerialize["departmentId"] = o.DepartmentId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.HireDate.IsSet() {
		toSerialize["hireDate"] = o.HireDate.Get()
	}
	if o.HourlyCost.IsSet() {
		toSerialize["hourlyCost"] = o.HourlyCost.Get()
	}
	if o.Iban.IsSet() {
		toSerialize["iban"] = o.Iban.Get()
	}
	if !IsNil(o.JobTitle) {
		toSerialize["jobTitle"] = o.JobTitle
	}
	if o.LastLogin.IsSet() {
		toSerialize["lastLogin"] = o.LastLogin.Get()
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if o.LastUpdated.IsSet() {
		toSerialize["lastUpdated"] = o.LastUpdated.Get()
	}
	if o.MonthlySalary.IsSet() {
		toSerialize["monthlySalary"] = o.MonthlySalary.Get()
	}
	if o.Phone.IsSet() {
		toSerialize["phone"] = o.Phone.Get()
	}
	if o.State.IsSet() {
		toSerialize["state"] = o.State.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.UserId.IsSet() {
		toSerialize["userId"] = o.UserId.Get()
	}
	if o.WeeklyHours.IsSet() {
		toSerialize["weeklyHours"] = o.WeeklyHours.Get()
	}
	if o.Zip.IsSet() {
		toSerialize["zip"] = o.Zip.Get()
	}
	return toSerialize, nil
}

type NullableEmployeeCreate struct {
	value *EmployeeCreate
	isSet bool
}

func (v NullableEmployeeCreate) Get() *EmployeeCreate {
	return v.value
}

func (v *NullableEmployeeCreate) Set(val *EmployeeCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeCreate(val *EmployeeCreate) *NullableEmployeeCreate {
	return &NullableEmployeeCreate{value: val, isSet: true}
}

func (v NullableEmployeeCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


