/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MagicLinkVerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagicLinkVerifyRequest{}

// MagicLinkVerifyRequest struct for MagicLinkVerifyRequest
type MagicLinkVerifyRequest struct {
	Token string `json:"token"`
}

type _MagicLinkVerifyRequest MagicLinkVerifyRequest

// NewMagicLinkVerifyRequest instantiates a new MagicLinkVerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagicLinkVerifyRequest(token string) *MagicLinkVerifyRequest {
	this := MagicLinkVerifyRequest{}
	this.Token = token
	return &this
}

// NewMagicLinkVerifyRequestWithDefaults instantiates a new MagicLinkVerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagicLinkVerifyRequestWithDefaults() *MagicLinkVerifyRequest {
	this := MagicLinkVerifyRequest{}
	return &this
}

// GetToken returns the Token field value
func (o *MagicLinkVerifyRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *MagicLinkVerifyRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *MagicLinkVerifyRequest) SetToken(v string) {
	o.Token = v
}

func (o MagicLinkVerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagicLinkVerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *MagicLinkVerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMagicLinkVerifyRequest := _MagicLinkVerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMagicLinkVerifyRequest)

	if err != nil {
		return err
	}

	*o = MagicLinkVerifyRequest(varMagicLinkVerifyRequest)

	return err
}

type NullableMagicLinkVerifyRequest struct {
	value *MagicLinkVerifyRequest
	isSet bool
}

func (v NullableMagicLinkVerifyRequest) Get() *MagicLinkVerifyRequest {
	return v.value
}

func (v *NullableMagicLinkVerifyRequest) Set(val *MagicLinkVerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMagicLinkVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMagicLinkVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagicLinkVerifyRequest(val *MagicLinkVerifyRequest) *NullableMagicLinkVerifyRequest {
	return &NullableMagicLinkVerifyRequest{value: val, isSet: true}
}

func (v NullableMagicLinkVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagicLinkVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


