/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StillePartnerZeile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StillePartnerZeile{}

// StillePartnerZeile struct for StillePartnerZeile
type StillePartnerZeile struct {
	Auseinandersetzungsguthaben string `json:"auseinandersetzungsguthaben"`
	Gewinnanteil string `json:"gewinnanteil"`
	Gewinnvortrag string `json:"gewinnvortrag"`
	Hinweis NullableString `json:"hinweis,omitempty"`
	InstrumentType string `json:"instrument_type"`
	Kest string `json:"kest"`
	Name string `json:"name"`
	VerlustVerrechnungskonto string `json:"verlust_verrechnungskonto"`
	Verlustanteil string `json:"verlustanteil"`
}

type _StillePartnerZeile StillePartnerZeile

// NewStillePartnerZeile instantiates a new StillePartnerZeile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStillePartnerZeile(auseinandersetzungsguthaben string, gewinnanteil string, gewinnvortrag string, instrumentType string, kest string, name string, verlustVerrechnungskonto string, verlustanteil string) *StillePartnerZeile {
	this := StillePartnerZeile{}
	this.Auseinandersetzungsguthaben = auseinandersetzungsguthaben
	this.Gewinnanteil = gewinnanteil
	this.Gewinnvortrag = gewinnvortrag
	this.InstrumentType = instrumentType
	this.Kest = kest
	this.Name = name
	this.VerlustVerrechnungskonto = verlustVerrechnungskonto
	this.Verlustanteil = verlustanteil
	return &this
}

// NewStillePartnerZeileWithDefaults instantiates a new StillePartnerZeile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStillePartnerZeileWithDefaults() *StillePartnerZeile {
	this := StillePartnerZeile{}
	return &this
}

// GetAuseinandersetzungsguthaben returns the Auseinandersetzungsguthaben field value
func (o *StillePartnerZeile) GetAuseinandersetzungsguthaben() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Auseinandersetzungsguthaben
}

// GetAuseinandersetzungsguthabenOk returns a tuple with the Auseinandersetzungsguthaben field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetAuseinandersetzungsguthabenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auseinandersetzungsguthaben, true
}

// SetAuseinandersetzungsguthaben sets field value
func (o *StillePartnerZeile) SetAuseinandersetzungsguthaben(v string) {
	o.Auseinandersetzungsguthaben = v
}

// GetGewinnanteil returns the Gewinnanteil field value
func (o *StillePartnerZeile) GetGewinnanteil() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gewinnanteil
}

// GetGewinnanteilOk returns a tuple with the Gewinnanteil field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetGewinnanteilOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gewinnanteil, true
}

// SetGewinnanteil sets field value
func (o *StillePartnerZeile) SetGewinnanteil(v string) {
	o.Gewinnanteil = v
}

// GetGewinnvortrag returns the Gewinnvortrag field value
func (o *StillePartnerZeile) GetGewinnvortrag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gewinnvortrag
}

// GetGewinnvortragOk returns a tuple with the Gewinnvortrag field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetGewinnvortragOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gewinnvortrag, true
}

// SetGewinnvortrag sets field value
func (o *StillePartnerZeile) SetGewinnvortrag(v string) {
	o.Gewinnvortrag = v
}

// GetHinweis returns the Hinweis field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StillePartnerZeile) GetHinweis() string {
	if o == nil || IsNil(o.Hinweis.Get()) {
		var ret string
		return ret
	}
	return *o.Hinweis.Get()
}

// GetHinweisOk returns a tuple with the Hinweis field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StillePartnerZeile) GetHinweisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hinweis.Get(), o.Hinweis.IsSet()
}

// HasHinweis returns a boolean if a field has been set.
func (o *StillePartnerZeile) HasHinweis() bool {
	if o != nil && o.Hinweis.IsSet() {
		return true
	}

	return false
}

// SetHinweis gets a reference to the given NullableString and assigns it to the Hinweis field.
func (o *StillePartnerZeile) SetHinweis(v string) {
	o.Hinweis.Set(&v)
}
// SetHinweisNil sets the value for Hinweis to be an explicit nil
func (o *StillePartnerZeile) SetHinweisNil() {
	o.Hinweis.Set(nil)
}

// UnsetHinweis ensures that no value is present for Hinweis, not even an explicit nil
func (o *StillePartnerZeile) UnsetHinweis() {
	o.Hinweis.Unset()
}

// GetInstrumentType returns the InstrumentType field value
func (o *StillePartnerZeile) GetInstrumentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstrumentType
}

// GetInstrumentTypeOk returns a tuple with the InstrumentType field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetInstrumentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstrumentType, true
}

// SetInstrumentType sets field value
func (o *StillePartnerZeile) SetInstrumentType(v string) {
	o.InstrumentType = v
}

// GetKest returns the Kest field value
func (o *StillePartnerZeile) GetKest() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kest
}

// GetKestOk returns a tuple with the Kest field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetKestOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kest, true
}

// SetKest sets field value
func (o *StillePartnerZeile) SetKest(v string) {
	o.Kest = v
}

// GetName returns the Name field value
func (o *StillePartnerZeile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StillePartnerZeile) SetName(v string) {
	o.Name = v
}

// GetVerlustVerrechnungskonto returns the VerlustVerrechnungskonto field value
func (o *StillePartnerZeile) GetVerlustVerrechnungskonto() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerlustVerrechnungskonto
}

// GetVerlustVerrechnungskontoOk returns a tuple with the VerlustVerrechnungskonto field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetVerlustVerrechnungskontoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerlustVerrechnungskonto, true
}

// SetVerlustVerrechnungskonto sets field value
func (o *StillePartnerZeile) SetVerlustVerrechnungskonto(v string) {
	o.VerlustVerrechnungskonto = v
}

// GetVerlustanteil returns the Verlustanteil field value
func (o *StillePartnerZeile) GetVerlustanteil() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Verlustanteil
}

// GetVerlustanteilOk returns a tuple with the Verlustanteil field value
// and a boolean to check if the value has been set.
func (o *StillePartnerZeile) GetVerlustanteilOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verlustanteil, true
}

// SetVerlustanteil sets field value
func (o *StillePartnerZeile) SetVerlustanteil(v string) {
	o.Verlustanteil = v
}

func (o StillePartnerZeile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StillePartnerZeile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auseinandersetzungsguthaben"] = o.Auseinandersetzungsguthaben
	toSerialize["gewinnanteil"] = o.Gewinnanteil
	toSerialize["gewinnvortrag"] = o.Gewinnvortrag
	if o.Hinweis.IsSet() {
		toSerialize["hinweis"] = o.Hinweis.Get()
	}
	toSerialize["instrument_type"] = o.InstrumentType
	toSerialize["kest"] = o.Kest
	toSerialize["name"] = o.Name
	toSerialize["verlust_verrechnungskonto"] = o.VerlustVerrechnungskonto
	toSerialize["verlustanteil"] = o.Verlustanteil
	return toSerialize, nil
}

func (o *StillePartnerZeile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auseinandersetzungsguthaben",
		"gewinnanteil",
		"gewinnvortrag",
		"instrument_type",
		"kest",
		"name",
		"verlust_verrechnungskonto",
		"verlustanteil",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStillePartnerZeile := _StillePartnerZeile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStillePartnerZeile)

	if err != nil {
		return err
	}

	*o = StillePartnerZeile(varStillePartnerZeile)

	return err
}

type NullableStillePartnerZeile struct {
	value *StillePartnerZeile
	isSet bool
}

func (v NullableStillePartnerZeile) Get() *StillePartnerZeile {
	return v.value
}

func (v *NullableStillePartnerZeile) Set(val *StillePartnerZeile) {
	v.value = val
	v.isSet = true
}

func (v NullableStillePartnerZeile) IsSet() bool {
	return v.isSet
}

func (v *NullableStillePartnerZeile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStillePartnerZeile(val *StillePartnerZeile) *NullableStillePartnerZeile {
	return &NullableStillePartnerZeile{value: val, isSet: true}
}

func (v NullableStillePartnerZeile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStillePartnerZeile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


