/*
SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

API version: 0.1.0
Contact: support@simplebilly.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package simplebillyapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductStock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductStock{}

// ProductStock struct for ProductStock
type ProductStock struct {
	Name string `json:"name"`
	ProductId string `json:"product_id"`
	Sku string `json:"sku"`
	StockQuantity NullableInt64 `json:"stock_quantity,omitempty"`
}

type _ProductStock ProductStock

// NewProductStock instantiates a new ProductStock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductStock(name string, productId string, sku string) *ProductStock {
	this := ProductStock{}
	this.Name = name
	this.ProductId = productId
	this.Sku = sku
	return &this
}

// NewProductStockWithDefaults instantiates a new ProductStock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductStockWithDefaults() *ProductStock {
	this := ProductStock{}
	return &this
}

// GetName returns the Name field value
func (o *ProductStock) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductStock) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductStock) SetName(v string) {
	o.Name = v
}

// GetProductId returns the ProductId field value
func (o *ProductStock) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *ProductStock) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *ProductStock) SetProductId(v string) {
	o.ProductId = v
}

// GetSku returns the Sku field value
func (o *ProductStock) GetSku() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sku
}

// GetSkuOk returns a tuple with the Sku field value
// and a boolean to check if the value has been set.
func (o *ProductStock) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sku, true
}

// SetSku sets field value
func (o *ProductStock) SetSku(v string) {
	o.Sku = v
}

// GetStockQuantity returns the StockQuantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProductStock) GetStockQuantity() int64 {
	if o == nil || IsNil(o.StockQuantity.Get()) {
		var ret int64
		return ret
	}
	return *o.StockQuantity.Get()
}

// GetStockQuantityOk returns a tuple with the StockQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProductStock) GetStockQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.StockQuantity.Get(), o.StockQuantity.IsSet()
}

// HasStockQuantity returns a boolean if a field has been set.
func (o *ProductStock) HasStockQuantity() bool {
	if o != nil && o.StockQuantity.IsSet() {
		return true
	}

	return false
}

// SetStockQuantity gets a reference to the given NullableInt64 and assigns it to the StockQuantity field.
func (o *ProductStock) SetStockQuantity(v int64) {
	o.StockQuantity.Set(&v)
}
// SetStockQuantityNil sets the value for StockQuantity to be an explicit nil
func (o *ProductStock) SetStockQuantityNil() {
	o.StockQuantity.Set(nil)
}

// UnsetStockQuantity ensures that no value is present for StockQuantity, not even an explicit nil
func (o *ProductStock) UnsetStockQuantity() {
	o.StockQuantity.Unset()
}

func (o ProductStock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductStock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["product_id"] = o.ProductId
	toSerialize["sku"] = o.Sku
	if o.StockQuantity.IsSet() {
		toSerialize["stock_quantity"] = o.StockQuantity.Get()
	}
	return toSerialize, nil
}

func (o *ProductStock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"product_id",
		"sku",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductStock := _ProductStock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductStock)

	if err != nil {
		return err
	}

	*o = ProductStock(varProductStock)

	return err
}

type NullableProductStock struct {
	value *ProductStock
	isSet bool
}

func (v NullableProductStock) Get() *ProductStock {
	return v.value
}

func (v *NullableProductStock) Set(val *ProductStock) {
	v.value = val
	v.isSet = true
}

func (v NullableProductStock) IsSet() bool {
	return v.isSet
}

func (v *NullableProductStock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductStock(val *ProductStock) *NullableProductStock {
	return &NullableProductStock{value: val, isSet: true}
}

func (v NullableProductStock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductStock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


